### ISSUE TITLE
Getting hardware information seems very slow

### ISSUE THREAD

**Issue by BullyWiiPlaza** [oshi/oshi#613] opened 2018-09-09 09:53 UTC
When using the code and `maven` dependency from [this](https://stackoverflow.com/a/37705082/3764804) `StackOverflow` answer, the runtime of the method is extremely slow. I've seen it take 10, 15 or even 50 seconds to complete. In the meantime `OSHI` writes the following logs to the console:

```
11:42:30.781 [pool-1-thread-1] DEBUG oshi.software.os.windows.WindowsOSVersionInfoEx - Initialized OSVersionInfoEx
11:43:18.815 [pool-1-thread-1] DEBUG oshi.hardware.common.AbstractCentralProcessor - Oracle MXBean detected.
11:43:46.044 [pool-1-thread-1] DEBUG oshi.hardware.platform.windows.WindowsCentralProcessor - Initialized Processor
```

Is there a problem with my code? Is the runtime "normal" or is there some kind of performance issue? My PC is quite modern, too. In my opinion this feels too slow for "only" getting a few hardware information so this nearly makes the library obsolete for the purpose of hardware-based license key generation since users don't appreciate to wait that long. Besides this, the library is excellent of course.

Thanks a lot for your time, Mr. Widdis.

**Comment by dbwiddis** [comment] 2018-09-09 13:41
The latency is due to initialization of WMI the first time.  If you re-run the program a second time within a short period you won't see the delay.   And it doesn't happen once OSHI is up and running polling periodically.

**Comment by dbwiddis** [comment] 2018-09-09 13:44
The delay is outside OSHI:  if you try a `wmic` query of the same information you'll get the long delay.    Unfortunately I've coded the initialization of the `CentralProcessor` object to grab the first set of CPU ticks so it can calculate usage between ticks the first time you call it.   I could, perhaps, remove this initialization unless/until it's asked for. 

Alternately, you can try turning on a WMI timeout:  `WmiUtil.setTimeout(1000);` will put a 1-second timeout on WMI calls. If you do this before initializing the processor, the tick query will fail (return 0's) after 1 second but other queries, such as for the hardware information, should complete just fine.   You can turn it back to infinite (timeout of -1) after you're done.

**Comment by dbwiddis** [comment] 2018-09-09 23:55
So I've been fighting this thing for a few years.  See #416 for some even worse examples.   Interestingly, Windows 10 and multiples of 20 seconds seem to be commonalities for the one remaining returring issue.

WMI uses RPC under the hood, and the 20 second timeout hints toward an RPC timeout.

My educated guess based on the symptoms is the following sequence:
* OSHI (or `wmic`) tries to execute a WMI query.
* If there's been a long delay since the last WMI query, the RPC server has to do some initialize/wakeup step
* The RPC call times out after 20 seconds and the WMI/COM code (under the hood) tries again, successful as the RPC server is now responsive.
* Future WMI calls are also successful as long as the RPC server doesn't idle out (I've found about 15 minutes to be the threshold.)

If I'm correct (again this is purely a guess), there may be a RPC-wakeup/COM/WMI race condition bug in Win10.  If this is the case, the strategy I mentioned in the previous comment should work (do a query with a short timeout, and if it fails try again.)  Almost all WMI queries in OSHI finish under 1000 ms, except for the disk/filesystem queries which tend to take up to 3000 seconds.  

Possible workarounds I can code into OSHI:
* Try to configure the RPC timeout.  [This page](https://docs.microsoft.com/en-us/windows/desktop/services/services-and-rpc-tcp) indicates there's a **SCMApiConnectionParam** registry value, although I didn't find it in a brief search or see if there's a programmatic way to change it.
* Try to work around the race condition by "waking up" the RPC server somehow.  (Direct code preferred; using a "dummy" WMI query with a short timeout may also work.)  And figuring out how long it takes to go back to sleep and maintaining a keepalive (or re-wakeup) strategy.

**Comment by dbwiddis** [comment] 2018-09-10 01:53
Or not.   🤦‍

Testing on my Win10 machine I'm getting those 40-second timeouts and it's not the first overall WMI query.  The error is in the first tick count query, but it should be getting that from Performance Counters, not WMI (except as a backup).   [This comment](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java#L263) shows I missed removing a debugging query.

Seeing if removing that fixes the problem.... of course I have to wait 15 minutes or more to test.

**Comment by dbwiddis** [comment] 2018-09-10 01:57
Confirmed:

> 2018-09-09 18:56:18.164 [INFO] SystemInfoTest - Checking Processor...
> 2018-09-09 18:56:18.295 [ERROR] WindowsCentralProcessor - Localized PROCESSOR: Processor
> 2018-09-09 18:56:18.297 [ERROR] WindowsCentralProcessor - Instances: [0, 1, 2, 3, _Total]
> 2018-09-09 18:56:18.300 [ERROR] WindowsCentralProcessor - I SHOULD NOT BE HERE
> 2018-09-09 18:56:51.196 [ERROR] WmiUtil - Long query: 32896 ms, SELECT [PERCENTDPCTIME, PERCENTINTERRUPTTIME, PERCENTPRIVILEGEDTIME, PERCENTPROCESSORTIME, PERCENTUSERTIME] FROM Win32_PerfRawData_PerfOS_Processor WHERE NOT Name="_Total"
> 2018-09-09 18:56:51.196 [ERROR] WindowsCentralProcessor - I SHOULD STILL NOT BE HERE

**Comment by dbwiddis** [comment] 2018-09-10 02:15
This should be fixed (well, the slow WMI query is still there but it shouldn't execute if you haven't disabled performance counters).  Can you check SNAPSHOT?

**Comment by dbwiddis** [comment] 2018-09-10 15:31
I just tested the latest on my Win10 system and got ~125 ms for the Processor initialization and ~1 second to collect all the ticks.  I'd really like to see your complete code with some log timestamps to see where the bottleneck still is.   It could just be that "WMI wakeup" I mentioned earlier that will happen with both `wmic` and OSHI, whichever runs first...

**Comment by dbwiddis** [comment] 2018-09-10 16:00
Also did you test any of the timeout suggestions?

**Comment by BullyWiiPlaza** [comment] 2018-09-12 22:00
Sorry for the delay. I will do some more testing shortly and let you know. I can already tell that the direct `wmic` solution is only slightly faster and may suffer from the spin up issue mentioned but it's not too bad (about 6 seconds at maximum but often also less than 1 second). The code from StackOverflow is exactly the one I was using (OSHI-wise).

**Comment by dbwiddis** [comment] 2018-10-08 08:33
Have you been able to do any more testing on OSHI or playing with RPC timeouts?

**Comment by BullyWiiPlaza** [comment] 2018-10-08 15:37
I was using my own implementation with `ProcessBuilder` and `wmic`. Furthermore I multi-threaded each component I wanted to read but I didn't only use `wmic`. This usually completed in 1 - 5 seconds in total so I had no issues in particular with `RPC` timeouts. Also, many users who ran the code didn't complain so I assume it was acceptable. Since it does what it should well, I don't really want to try `OSHI` anymore in this context but thanks for the reminder.

**Comment by dbwiddis** [comment] 2018-10-08 18:47
OK, fair enough!  I think OSHI is at least as fast as wmic, but since you've got something working I'll close this issue.

**Closed by dbwiddis** 2018-10-08 18:47 UTC
Labels: confirmed bug, fixed?
