### ISSUE TITLE
UsbDevice

### ISSUE THREAD

**Issue by paulosantos071** [oshi/oshi#1763] opened 2021-11-11 16:49 UTC
Hello,
I'm trying to bring up the list of devices connected through the usb port right now, but apparently I'm getting the information from all devices that have already been connected and not just the current one, how do I do it?

![image](https://user-images.githubusercontent.com/79267625/141333731-7f0a8eae-6c14-4df6-aa26-7eb8af11fb38.png)
![image](https://user-images.githubusercontent.com/79267625/141336750-24435593-f771-4081-8f33-be290a9dd042.png)

**Comment by dbwiddis** [comment] 2021-11-11 18:48
It's not clear what error you are reporting.

The code walks the Windows Device Tree starting from the USB Controllers, to find all connected devices.  So it is expected to return the whole list each time.  You would have to compare lists between successive calls in order to identify devices added or removed.

Is the problem that a device has been removed and is still showing in the list?

**Comment by paulosantos071** [comment] 2021-11-11 18:55
Yes, I want to return only the usb controllers connected at the time I ran, from that device tree I am not able to extract any information, as I am a beginner in java I am having a certain difficulty in understanding.

**Comment by dbwiddis** [comment] 2021-11-11 19:06
That is what the list is supposed to be showing.  You can use `false` as the parameter to just get a flat list of devices instead of the tree-based output.   Can you point out which device should not be in the above output?

**Comment by dbwiddis** [comment] 2021-11-19 16:36
Closing this as it seems to be performing as designed.  Let me know if you think there's a bug, with a few more details on exactly what the error is.

**Closed by dbwiddis** 2021-11-19 16:36 UTC
Labels: question
