### ISSUE TITLE
Sensor methods returns only zeros.

### ISSUE THREAD

**Issue by KaVzaQ** [oshi/oshi#386] opened 2017-07-16 14:07 UTC
Everything works perfectly fine... but not sensors. I have installed of course OpenHardwareMonitor.
I ran SystemInfoTest and...

`Sensors:`
 `CPU Temperature: 0,0°C`
 `Fan Speeds: [0]`
` CPU Voltage: 0,0V`

Any help?
I have 
`AMD Ryzen 5 1600 Six-Core Processor`
` 6 physical CPU(s)`
` 12 logical CPU(s)`
`Identifier: AMD64 Family 23 Model 1 Stepping 1`
`ProcessorID: 178BFBFF00800F11`

**Comment by dbwiddis** [comment] 2017-07-16 16:31
OpenHardwareMonitor is only programmed to be helpful for Windows systems. Which OS are you using?

**Comment by ejaszewski** [comment] 2017-07-16 17:01
It also looks like OHM doesn't support Ryzen yet, so that could also be the cause of the zero readings.

**Comment by KaVzaQ** [comment] 2017-07-16 17:17
I'm using Windows 10 Proffesional.

Yeah, I think the same because I don't see any temperature readings of my cpu in OHM app. Thats sad because ryzen is 3 months old already...

**Comment by dbwiddis** [comment] 2017-07-16 17:26
Ah. I'm going to close this because there's nothing OSHI can do. It's faithfully reporting the lack of info in OHM. :)

**Closed by dbwiddis** 2017-07-16 17:26 UTC

**Comment by ejaszewski** [comment] 2017-07-16 17:27
Unfortunately, seems like there might not be Ryzen support for a while, given that Skylake only got support last November.
