### ISSUE TITLE
Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

### ISSUE THREAD

**Issue by shanmukhateja** [oshi/oshi#717] opened 2018-12-08 05:28 UTC
**Background:**
I'm a first timer trying to resolve the issue #702 and I have been following the CONTRIBUTING.md file. I cloned the project, installed maven (`sudo apt install maven`) and then ran `mvn test` as per the CONTRIBUTING.md
I got the following error:
`Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter `

I then tried using `mvnw test` file on ~/oshi/ directory but still got the same error.

However, with a quick Google search, I ended up [here](https://stackoverflow.com/a/50661649) which said to add the following line to **pom.xml**:
`<useSystemClassLoader>false</useSystemClassLoader>`

I am now finally able to run tests. I am creating this issue so that newcomers like me wouldn't have to go through this again.

OS: Debian Stretch x64
Maven version 3.3.9
Java: openjdk version "1.8.0_181"

**Comment by BilalAM** [comment] 2018-12-08 17:09
I heard of this exception , this was a valid bug and the solution is to upgrade your jdk , also if that still persists then update your maven version . If the problem still persists then look at your environment variables , usually stuff like this happens due to this .

**Comment by shanmukhateja** [comment] 2018-12-09 11:53
Good to know. 

> the solution is to upgrade your jdk

@BilalAM do you mean use JDK 11?

**Comment by dbwiddis** [comment] 2018-12-09 17:20
Browsing the [upstream issue](https://issues.apache.org/jira/browse/SUREFIRE-1588), Oracle Java 1.8.0_191 is mentioned.  Not sure if that is the point that causes the issue or fixes it, though...

Given the bug is fixed in 3.0.0-M1 I think this may be the best solution.

**Comment by dbwiddis** [comment] 2018-12-12 00:04
Looking in detail at the [upstream issue](https://issues.apache.org/jira/browse/SUREFIRE-1588):

- The issue appears to have been introduced in Oracle and OpenJDK 1.8.0_181 when backporting some Java 10 features (and claimed as a security feature, not a bug).
- It only appears to affect Debian-based Linux distros.
- Downgrading to an earlier Java version removes the stricter check causing the issue.  [Upgrading to 1.8.0_191 (on Debian distros) also appears to resolve this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925#97) with default settings which disable the check, at least temporarily.
- The Maven surefire plugin fixed this in 3.0.0-M1 and has no intention on fixing the 2.x branch past 2.22.1.

Fixes:
- Do nothing (yet) Have anyone affected by this issue (Debian users) update their JVM.
- Do nothing (yet) but if you want to build, add `-DskipTests` for the build and then run `mvn test` separately later.
- Set `useSystemClassLoader = false` in the pom.  This is a workaround and may be an appropriate temporary step until we upgrade the plugin version, but I'm leaning away from it.
- Set `forkCount` to 0 in the surefire plugin.  This could make slower builds.
- Upgrade the surefire plugin to 3.0.0-M1.  Not sure why we can't just do this now, and I think this is the best option from a project standpoint, rather than playing with workarounds.

**Closed** 2018-12-12 00:57 UTC
