### ISSUE TITLE
The order of logical processors changes every time.

### ISSUE THREAD

**Issue by kingkong3** [oshi/oshi#2076] opened 2022-06-20 23:42 UTC
Hello, I am developing a cpu monitoring tool using oshi and java.

We are developing a tool to monitor usage per numa of servers.

First, let me summarize my source code :

		//In Thread
		@Override
		public void run() {
			while(state) {
			try {
				// 1. Make cpuInfo by mapping NUMA numbers to each processor number.
				GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_CPU_UTILITY, true);
				
				SystemInfo si = new SystemInfo(); 
				CentralProcessor cpu = si.getHardware().getProcessor();
				List<LogicalProcessor> list = cpu.getLogicalProcessors();
				
				Map<Integer, Integer> cpuInfo = null;
				for(LogicalProcessor lp : list) {
					int numa = lp.getNumaNode();
					cpuInfo.put(lp.getPhysicalProcessorNumber(), numa);
				}
				
				//2. Get cpu load data
				long[][] oldTicks = cpu.getProcessorCpuLoadTicks();
				
				Thread.sleep(1000);
				
				double [] values = cpu.getProcessorCpuLoadBetweenTicks(oldTicks);
				
				//3. Get cpu load by numa
				int numaNumber = 0;
				Map<Integer, Double> cpuValueMap = new ConcurrentHashMap<Integer, Double>();
				for(int index=0; index< values.length; index++) {
					numaNumber = cpuInfo.get(index);
					
					if(!cpuValueMap.containsKey(numaNumber)) {
						cpuValueMap.put(numaNumber, values[index]);
					}else {
						cpuValueMap.put(numaNumber, cpuValueMap.get(numaNumber) + values[index]);
					}
				}
				
				//numa's count
				int numaCount = cpuValueMap.keySet().size();
				int cpuCount =  (int)(cpuInfo.size()/numaCount);
				
				Set<Integer> numaSet = cpuValueMap.keySet();
				for(Integer numa : numaSet) {
					cpuValueMap.put(numa, (double)Math.round(((cpuMap.get(numa)/cpuCount)*100)*100/100.0));	 
				}
				
				
				//Then, cpuValueMap({numa:value, numa:value}) is {0:27.0, 1:64.0, 2:28.0, 3:66.3}
				
			}catch(Exception e) {
				e.printStackTrace();
			}
		}
	}

My Server's LogicalProcessor : 
LogicalProcessor [processorNumber=0, coreNumber=0, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=1, coreNumber=1, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=2, coreNumber=2, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=3, coreNumber=3, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=4, coreNumber=4, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=5, coreNumber=5, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=6, coreNumber=6, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=7, coreNumber=13, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=8, coreNumber=16, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=9, coreNumber=18, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=10, coreNumber=20, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=11, coreNumber=22, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=12, coreNumber=24, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=13, coreNumber=26, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=14, coreNumber=28, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=15, coreNumber=30, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=16, coreNumber=32, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=17, coreNumber=34, packageNumber=0, numaNode=0, processorGroup=0]

LogicalProcessor [processorNumber=0, coreNumber=7, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=1, coreNumber=8, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=2, coreNumber=9, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=3, coreNumber=10, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=4, coreNumber=11, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=5, coreNumber=12, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=6, coreNumber=14, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=7, coreNumber=15, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=8, coreNumber=17, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=9, coreNumber=19, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=10, coreNumber=21, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=11, coreNumber=23, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=12, coreNumber=25, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=13, coreNumber=27, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=14, coreNumber=29, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=15, coreNumber=31, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=16, coreNumber=33, packageNumber=1, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=17, coreNumber=35, packageNumber=1, numaNode=1, processorGroup=1]

LogicalProcessor [processorNumber=18, coreNumber=36, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=19, coreNumber=38, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=20, coreNumber=40, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=21, coreNumber=42, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=22, coreNumber=44, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=23, coreNumber=46, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=24, coreNumber=48, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=25, coreNumber=50, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=26, coreNumber=52, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=27, coreNumber=54, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=28, coreNumber=56, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=29, coreNumber=58, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=30, coreNumber=60, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=31, coreNumber=62, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=32, coreNumber=64, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=33, coreNumber=66, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=34, coreNumber=68, packageNumber=2, numaNode=2, processorGroup=1]
LogicalProcessor [processorNumber=35, coreNumber=70, packageNumber=2, numaNode=2, processorGroup=1]

LogicalProcessor [processorNumber=18, coreNumber=37, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=19, coreNumber=39, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=20, coreNumber=41, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=21, coreNumber=43, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=22, coreNumber=45, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=23, coreNumber=47, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=24, coreNumber=49, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=25, coreNumber=51, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=26, coreNumber=53, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=27, coreNumber=55, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=28, coreNumber=57, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=29, coreNumber=59, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=30, coreNumber=61, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=31, coreNumber=63, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=32, coreNumber=65, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=33, coreNumber=67, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=34, coreNumber=69, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=35, coreNumber=71, packageNumber=3, numaNode=3, processorGroup=1]

Windows Server 2016
Xeon Gold 6254 4 processor
socket 4, core 72, LogicalProcessor 72, virtural noUse, hyper V Yes

The output Print changes the order of Logical Processor for each output.

**Comment by dbwiddis** [comment] 2022-06-20 23:45
Which OS?  Can you give an example?

**Comment by kingkong3** [comment] 2022-06-21 00:37
> Which OS? Can you give an example?

Sorry, I pressed the wrong enter and the issue went up before writing the contents. I fixed the issue.

**Comment by dbwiddis** [comment] 2022-06-21 04:46
OK, so this is WIndows, and you have a processor with >=64 cores, introducing processor groups.

OSHI consistently sorts (or is supposed to) by NUMA node and then logical processor.   Logical processor is determined by the bitmask, which is assocaited with the processor group.

It looks like Windows has mapped each of your 4 physical cores to a NUMA node, and the output is sorted in that order, with nodes 0, 1, 2, and 3 in that order.

Following that it is using the bitmask-based processor number.

And here is where there's obviously a bug somewhere.  The bitmask + processor group should be unique but there are two sets of cores 18-35 on processor group 1.

This may require a bit more debugging info.  I'll see if I can figure out anything just from this output and the source code first.

You state that it "changes every time".  What other output do you see?

**Comment by kingkong3** [comment] 2022-06-21 06:01
> OK, so this is WIndows, and you have a processor with >=64 cores, introducing processor groups.
> 
> OSHI consistently sorts (or is supposed to) by NUMA node and then logical processor. Logical processor is determined by the bitmask, which is assocaited with the processor group.
> 
> It looks like Windows has mapped each of your 4 physical cores to a NUMA node, and the output is sorted in that order, with nodes 0, 1, 2, and 3 in that order.
> 
> Following that it is using the bitmask-based processor number.
> 
> And here is where there's obviously a bug somewhere. The bitmask + processor group should be unique but there are two sets of cores 18-35 on processor group 1.
> 
> This may require a bit more debugging info. I'll see if I can figure out anything just from this output and the source code first.
> 
> You state that it "changes every time". What other output do you see?

The server where the bug is found is delivered to a difficult site.
Therefore, I would like to tell you that it is difficult to hand over the exact sample.

As far as I remember, the overall output was the same. However, the order of the output has changed every time.

**Comment by dbwiddis** [comment] 2022-06-21 17:30
> The server where the bug is found is delivered to a difficult site.

As noted in the README one of our biggest testing gaps is servers with >64 logical processors like that one, which help identify processor groups.   If possible it would be really helpful to get some instrumented debug output from that machine that will help me double-check OSHI's code.  Do you think that would be possible?

> As far as I remember, the overall output was the same. However, the order of the output has changed every time.

The first level sorting should always be by NUMA node and on the same node, the second sort should be by logical processor number based on the group bitmask.  That works consistently for the first three groups above, but then the fourth group repeats the LP numbers, which is clearly an error (or perhaps the third group is an error and the fourth one correct).  The good news is for the purposes of your NUMA node code calculation, the values should work out (although I'm not sure the processor utility calculation works if you re-instantiate SystemInfo every time in your loop).  The only issue with the ordering is the core numbering.

Digging through the code, I did find two (of the same type) errors here:
https://github.com/oshi/oshi/blob/41f88342ea8e16bd1a832507bd804db1bd3c9f65/oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java#L103-L108

The intention was to take the bit number and add 64 * processor group to it, but using the longValue of the mask is actually taking very large numbers (including a large negative number for bit 63) and adding 64 to it makes the sorting somewhat as intended for the first 7 bits but then produces an alternating pattern for the remainder.  That can be seen in the output above where cores 0-6 are in the first group and 7-12 are in the second group, 13 is unpredictable due to a tie, and starting with 14 they assign alternately to the two groups.   This mis-sorting may also later impact the core and package numbers, likely explaining the duplicated values in the third and fourth groups in your output.

I'll put together a fix for this within a few hours.

**Comment by kingkong3** [comment] 2022-06-21 23:45
Thank you very much for your quick response.

I will visit the site as soon as possible and test the latest version.
 -- [oshi-core-6.2.0-20220621.181905-23.jar] Is this the latest SNAPSHOT?

The process of visiting the site is a bit complicated, and I also have another schedule, so I think the visit schedule will be next week at the earliest.

However, when I visit, I will try to bring as many output cases of the logical processor as possible.

Thank you again for your hard work, and I will leave a reply after visiting.

**Comment by dbwiddis** [comment] 2022-06-22 00:05
> I will visit the site as soon as possible and test the latest version. -- [oshi-core-6.2.0-20220621.181905-23.jar] Is this the latest SNAPSHOT?

As of now it is. New snapshots are published whenever there are commits to the master branch, so any datestamp newer than that should help.  The snapshots are also published to the central repository so updating the version there to 6.2.0-SNAPSHOT should pull the latest one.

> However, when I visit, I will try to bring as many output cases of the logical processor as possible.

It would also be very helpful if you can run a command to query the processor names, which are a combination of NUMA node and processor number to check vs. OSHI's list.  From a command prompt:
```
wmic path Win32_PerfRawData_Counters_ProcessorInformation get Name
```

**Comment by kingkong3** [comment] 2022-06-28 04:10
I am planning to visit the site tomorrow, and I changed the library from the existing source code and ran it, but the following error occurs.

what can i do for this?

![image](https://user-images.githubusercontent.com/23719336/176090381-afdd3dc4-e444-4dad-b89f-b62adc5ab0ea.png)

**Comment by dbwiddis** [comment] 2022-06-28 04:12
You need to update JNA to 5.12.0.

**Comment by kingkong3** [comment] 2022-06-28 04:17
> You need to update JNA to 5.12.0.

Thank you very much.

I will test it tomorrow using this lib.

And as you requested, I will write down the result of the command below and the sample of the logical processor list.

          wmic path Win32_PerfRawData_Counters_ProcessorInformation get Name

**Comment by dbwiddis** [comment] 2022-06-28 04:31
> And as you requested, I will write down the result of the command below and the sample of the logical processor list.

Awesome. It's really hard to find machines with more than 64 logical processors to double-check OSHI's Processor Group code, so this is very useful!

**Comment by kingkong3** [comment] 2022-06-29 08:15
Hello! As a result of the test in the field, the cpuInfo was printed the same as the change.

     wmic path Win32_PerfRawData_Counters_ProcessorInformation get Name

Below is the result of the above command.

NAME    _Total
3,    _Total
3,    17
3,    16
...
3,    0
2,    _Total
2,    17
2,    16
...
2,    0
1,    _Total
1,    17
...
1,    0
0,    _Total
0,    17
...
0,    0


Below are the results of method [getLogicalProcessors.]

LogicalProcessor [processorNumber=0, coreNumber=0, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=1, coreNumber=1, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=2, coreNumber=2, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=3, coreNumber=3, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=4, coreNumber=4, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=5, coreNumber=5, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=6, coreNumber=6, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=7, coreNumber=7, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=8, coreNumber=8, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=9, coreNumber=9, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=10, coreNumber=10, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=11, coreNumber=11, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=12, coreNumber=12, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=13, coreNumber=13, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=14, coreNumber=14, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=15, coreNumber=15, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=16, coreNumber=16, packageNumber=0, numaNode=0, processorGroup=0]
LogicalProcessor [processorNumber=17, coreNumber=17, packageNumber=0, numaNode=0, processorGroup=0]

LogicalProcessor [processorNumber=0, coreNumber=36, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=1, coreNumber=37, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=2, coreNumber=38, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=3, coreNumber=39, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=4, coreNumber=40, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=5, coreNumber=41, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=6, coreNumber=42, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=7, coreNumber=43, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=8, coreNumber=44, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=9, coreNumber=45, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=10, coreNumber=46, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=11, coreNumber=47, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=12, coreNumber=48, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=13, coreNumber=49, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=14, coreNumber=50, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=15, coreNumber=51, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=16, coreNumber=52, packageNumber=2, numaNode=1, processorGroup=1]
LogicalProcessor [processorNumber=17, coreNumber=53, packageNumber=2, numaNode=1, processorGroup=1]

LogicalProcessor [processorNumber=18, coreNumber=18, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=19, coreNumber=19, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=20, coreNumber=20, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=21, coreNumber=21, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=22, coreNumber=22, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=23, coreNumber=23, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=24, coreNumber=24, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=25, coreNumber=25, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=26, coreNumber=26, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=27, coreNumber=27, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=28, coreNumber=28, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=29, coreNumber=29, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=30, coreNumber=30, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=31, coreNumber=31, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=32, coreNumber=32, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=33, coreNumber=33, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=34, coreNumber=34, packageNumber=1, numaNode=2, processorGroup=0]
LogicalProcessor [processorNumber=35, coreNumber=35, packageNumber=1, numaNode=2, processorGroup=0]

LogicalProcessor [processorNumber=18, coreNumber=54, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=19, coreNumber=55, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=20, coreNumber=56, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=21, coreNumber=57, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=22, coreNumber=58, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=23, coreNumber=59, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=24, coreNumber=60, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=25, coreNumber=61, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=26, coreNumber=62, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=27, coreNumber=63, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=28, coreNumber=64, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=29, coreNumber=65, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=30, coreNumber=66, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=31, coreNumber=67, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=32, coreNumber=68, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=33, coreNumber=69, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=34, coreNumber=70, packageNumber=3, numaNode=3, processorGroup=1]
LogicalProcessor [processorNumber=35, coreNumber=71, packageNumber=3, numaNode=3, processorGroup=1]

I have one question.

![image](https://user-images.githubusercontent.com/23719336/176386635-bae85997-3387-4815-8396-0fde69e1762e.png)

As shown in the attached image, the task manager and I have a specific part of the tool, and there are different areas, so what should we consider to be the reason for this?

**Comment by dbwiddis** [comment] 2022-06-29 16:30
Great, looks like the numbering bug is fixed.   As for the differences in outputs, your code sample above instantiates a new SystemInfo inside the loop each time.  The CPU Utility calculation adjustments use that first set of ticks as a base to calculate differences from, but you're re-generating the base each time, and essentially doing the "time based" calculation that doesn't match Windows.

Instantiate SystemInfo and the CPU object once, outside your loop.  After that the rest should probably line up.

**Closed** 2022-06-30 02:56 UTC
Labels: confirmed bug, fixed

**Comment by kingkong3** [comment] 2022-06-30 03:29
> 

Thank you!
