### ISSUE TITLE
OSProcess.getUptime() sometimes return negative numbers on linux

### ISSUE THREAD

**Issue by Space2Man** [oshi/oshi#623] opened 2018-09-19 14:57 UTC
While monitoring processes I noticed that for some processes on my system the uptime is reported as negative number ... See how the uptime changes:

```
19/Sep/2018 16:51:29,224- INFO  ProcessStats: Found process java with uptime -45463780973
19/Sep/2018 16:51:53,119- INFO  ProcessStats: Found process java with uptime -45463757055
19/Sep/2018 16:52:53,084- INFO  ProcessStats: Found process java with uptime -45463697081
19/Sep/2018 16:53:53,030- INFO  ProcessStats: Found process java with uptime -45463637130
19/Sep/2018 16:54:53,025- INFO  ProcessStats: Found process java with uptime -45463577130
```

So far I noticed this only on Linux.

Thanks and best regards, Space

**Comment by dbwiddis** [comment] 2018-09-20 05:15
Also note there was a previous bug that was fixed in #611 which was in the 3.8.2 release.  Please confirm you're using the latest version.

**Comment by Space2Man** [comment] 2018-09-20 05:42
Hi,

I am on 3.8.3. 

```
# cat /proc/27730/stat
27730 (java) S 1896 27730 27730 0 -1 4202752 469155723 2903 24964 13 72774339 27705329 5 51 20 0 83 0 3727913584 15350476800 1828686 18446744073709551615 4194304 4196468 140723191714176 140723191696704 139668168816333 0 0 0 16800975 18446744073709551615 0 0 17 2 0 0 125 0 0
```

```
{
	"27730": {
		"userID": "102",
		"openFiles": 21399,
		"bytesRead": 16574021632,
		"parentProcessID": 1896,
		"path": "/opt/jdk/bin/java",
		"startTime": 1573066961149,
		"name": "java",
		"priority": 20,
		"threadCount": 83,
		"user": "",
		"group": null,
		"processID": 27730,
		"userTime": 1516073041,
		"currentWorkingDirectory": "",
		"groupID": "102",
		"virtualSize": 15350448128,
		"kernelTime": 577152666,
		"upTime": -35645817116,
		"commandLine": "/opt/jdk/bin/java\u0000-Xms6g\u0000-Xmx6g\u0000-Djava.awt.headless=true\u0000-XX:+UseParNewGC\u0000-XX:+UseConcMarkSweepGC\u0000-XX:CMSInitiatingOccupancyFraction=75\u0000-XX:+UseCMSInitiatingOccupancyOnly\u0000-XX:+HeapDumpOnOutOfMemoryError\u0000-XX:+DisableExplicitGC\u0000-Dfile.encoding=UTF-8\u0000-Djna.nosys=true\u0000-Des.path.home=/usr/share/elasticsearch\u0000-cp\u0000/usr/share/elasticsearch/lib/elasticsearch-2.4.6.jar:/usr/share/elasticsearch/lib/*\u0000org.elasticsearch.bootstrap.Elasticsearch\u0000start\u0000",
		"bytesWritten": 3836629749760,
		"residentSetSize": 7490310144,
		"state": "SLEEPING"
	}
}
```

```
20/Sep/2018 07:36:10,879- DEBUG LinuxOperatingSystem: Youngest PID is 64215 with 2022126480 jiffies
20/Sep/2018 07:36:10,979- DEBUG LinuxOperatingSystem: Start time in secs: 4.2019676E7
20/Sep/2018 07:36:11,015- DEBUG LinuxOperatingSystem: lsb_release -a: Distributor ID:   CentOS
20/Sep/2018 07:36:11,015- DEBUG LinuxOperatingSystem: lsb_release -a: Description:      CentOS release 6.7 (Final)
20/Sep/2018 07:36:11,086- DEBUG LinuxOperatingSystem: Youngest PID is 64215 with 2022126480 jiffies
20/Sep/2018 07:36:11,090- DEBUG LinuxOperatingSystem: Start time in secs: 4.2019676E7
```

I will provide the output of LinuxOperatingSystem.getHz()  soon. Could it be related to the uptime?

```
# uptime
 07:42:06 up 486 days,  8:13,  1 user,  load average: 0.31, 0.34, 0.40
```

**Comment by Space2Man** [comment] 2018-09-20 05:51
And the output of getHz():

`getHz: 48
`

**Comment by dbwiddis** [comment] 2018-09-20 05:55
Could be something with the uptime.  Can you post the contents of `/proc/uptime` please?

**Comment by Space2Man** [comment] 2018-09-20 05:57
```
# cat /proc/uptime
42020930.89 160623813.80
```

**Comment by dbwiddis** [comment] 2018-09-20 07:03
The 22nd element of your `proc/27730/stat` output is 3727913584.  OSHI assumes that this is the start time of the process in [clock ticks after boot](http://man7.org/linux/man-pages/man5/proc.5.html).  Using the 48 ticks per sec conversion, this works out to 77,664,866 seconds, or nearly 899 days.  Given the up time of a mere 42,020,930.89 seconds (486 days) this is obviously impossible.

So the Hz calculation is suspicious.  The default is 1000.  

For Hz, we get the highest PID # process (assumed to either be youngest, or "young enough").  Per your logfile, pid 64215 had a start time of 2022126480 ticks after boot.   We just need seconds after boot.   We know "now" seconds after boot (42M) so we just need to subtract off the seconds that the youngest process (64215) was running.  For that, the command is: `ps -p 64215 -o etimes=`.

Can you try that command on your highest PID process?

**Comment by Space2Man** [comment] 2018-09-20 07:57
[root@eisvm037 ~]# ps -p 64215 -o etime
    ELAPSED
252-09:28:03

**Comment by Space2Man** [comment] 2018-09-20 07:58
For init it matches the "uptime":

```
[root@eisvm037 ~]# ps -p 1 -o etime
    ELAPSED
486-10:29:39
```

**Comment by Space2Man** [comment] 2018-09-20 08:01
Issue is this is not the youngest process ... pid has already rolled over. E.g. the shell where I am logged on with is:

```
# ps -p 53834 -o etime
    ELAPSED
      05:47
```

**Comment by Space2Man** [comment] 2018-09-20 08:07
Since you do the HZ calculation only at init, wouldn't it be possible to start a process (like sleep 1) and calculate the HZ via that process stats?

**Comment by Space2Man** [comment] 2018-09-20 08:26
This looks complicated but it's the way procps (top, ps, ...) calculate the HZ value:

[https://github.com/soarpenguin/procps-3.0.5/blob/master/proc/sysinfo.c#L91](https://github.com/soarpenguin/procps-3.0.5/blob/master/proc/sysinfo.c#L91)

**Comment by dbwiddis** [comment] 2018-09-20 17:26
The comment on that source code is pure win. :)  

The code doesn't look too complicated, actually.  It simply fetches cpu ticks from `/proc/stat` and matches them up to the uptime.

The complicated part is where It improves on that basic comparison (the complicated part) by sampling uptime before/after, ensuring accurate enough resolution, and then uses a switch/case to round to known constants if in range.  (Sadly I can't steal that particular implementation for OSHI as it's GPL licensed.)

I should have done the `/proc/stat` calculation the first time in OSHI, instead of hunting down a process (with lower resolution up time)... initially I iterated all processes to get the youngest, which didn't hit performance but did trigger alerts on someone's monitoring software!  I thought the highest pid = "youngest or young enough" was a sound assumption until now.  "Young enough" is accounted for with a process uptime offset, but the line "Etime is {} seconds" is missing from your log output, so it wasn't able to fetch your elapsed time (note the `etimes=` syntax, curious what your output is for that) and the "it should be close to 0" assumption there breaks down.

Clearly the current implementation is both overcomplicated, and flawed, and I should just compare jiffies to uptime like a sane person would.

**Comment by dbwiddis** [comment] 2018-09-21 06:18
So as I was digging through the man files to see which `/proc/stat` values to add up to the total up time, I saw this note on the "idle" counter entry:

>                      idle   (4) Time spent in the idle task.  This value
>                             should be USER_HZ times the second entry in the
>                             /proc/uptime pseudo-file.

This is actually an improvement on the link you provided (although the brilliance of the comment should be again restated.)  In fact, I think that code may be flawed in that it adds up `/proc/stat` ticks which may, in a multi-processor system, actually exceed the number of jiffies.

**Comment by dbwiddis** [comment] 2018-09-21 06:43
Can you test the fix in #626?  It's in SNAPSHOT or you can fork my repo.

**Comment by dbwiddis** [comment] 2018-09-21 08:16
Note: I did write the author of the linked code (and awesome comment).  He was the author of `ps`, so I'm pretty sure the approach is sound... and he agreed with my approach using idle time for current kernels.  When he wrote the code, multi-core processors were rather rare, and it was intended to be Kernel 2.0 compatible...

**Closed** 2018-09-21 08:42 UTC
Labels: confirmed bug, fixed?

**Comment by Space2Man** [comment] 2018-09-21 18:01
Hi, will test next week :)

**Comment by dbwiddis** [comment] 2018-09-21 19:02
OK, I merged the fix and closed this issue, but feel free to reopen if it didn't work.  Once you test I'll cut another patch release.

**Comment by Space2Man** [comment] 2018-09-24 08:05
@dbwiddis Can I download the 3.9.0-SNAPSHOT via maven someplace?

**Comment by Space2Man** [comment] 2018-09-24 08:17
Never mind, I got it running ... missed the download on the start page :)

**Comment by Space2Man** [comment] 2018-09-24 08:43
@dbwiddis Unfortunately my test systems have been migrated and rebooted over the weekend ... But I tested on a different system where the highest PID is not the most current one and there it reports 100Hz which looks sane to me ... also the uptime reported looks sane.

So from my point of view the issue is solved. Thanks a lot!

**Comment by dbwiddis** [comment] 2018-09-24 20:01
Glad you found the jar download.  You can also usually just add the SNAPSHOT version and include this in your maven distribution management section:
```
		<snapshotRepository>
			<id>sonatype-nexus-snapshots</id>
			<name>Sonatype Nexus Snapshots</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
```
