### ISSUE TITLE
Unmapped relationship: 7

### ISSUE THREAD

**Issue by ohalushchak** [oshi/oshi#1780] opened 2021-11-19 07:29 UTC
Failed to get CPU info after an update to Windows 11.

`java.lang.IllegalStateException: Unmapped relationship: 7
	at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:3033)
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715)
	at oshi.driver.windows.LogicalProcessorInformation.getLogicalProcessorInformationEx(LogicalProcessorInformation.java:61)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:155)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:74)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:66)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:60)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68)`

**Comment by dbwiddis** [comment] 2021-11-19 15:40
This is a duplicate of #1554 (and #1699).  It can be resolved by updating JNA to at least version 5.8.0, although I recommend you use the latest version, 5.10.0.

**Closed** 2021-11-19 16:37 UTC
