### ISSUE TITLE
Windows version parsing is broken since v 5.2.1

### ISSUE THREAD

**Issue by Anonymenus** [oshi/oshi#1518] opened 2021-02-05 08:17 UTC
what I used to find info :
String OSVersion = systemInfo.getOperatingSystem().getVersionInfo().getVersion();
 It used to return like. 'windows server 2012 R2' ,and now it return ' windows 6.3'

what I should get the old info. while I refuse to update the jar file

**Comment by dbwiddis** [comment] 2021-02-05 08:22
Which version of OSHI were you using before and which one are you using now?

**Comment by Anonymenus** [comment] 2021-02-05 08:24
I used to use 5.2.1. now I used 5.4.1

**Comment by dbwiddis** [comment] 2021-02-05 08:44
There have been no changes to the windows version parsing code since 2020-07-07 which was a week before the 5.2.1 release.

The version is parsed from the file [`oshi.windows.versions.properties`](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/resources/oshi.windows.versions.properties) which is present in the JAR file and should be available on your classpath.  If you have a conflicting version of this file without the appropriate lookup line it may fail.

![image](https://user-images.githubusercontent.com/9291703/107010458-39829780-674b-11eb-9cdf-9a8ce70a0b39.png)

**Comment by Anonymenus** [comment] 2021-02-05 08:53
ok thank u, maybe it's individual ,I will see other hosts situation,I will contact with u if I have other question

**Comment by Anonymenus** [comment] 2021-02-05 09:39
hei, sorry,I have told u that I check the jar version again ,found it's version is 5.2.0, and return 'windows server 2012 R2'  and i change the version to 5.2.1 ,then it turned out different.

**Comment by dbwiddis** [comment] 2021-02-05 16:26
Well, that makes a little more sense. "Never worked" is more likely than "Worked and then stopped working."

Still, the solution is the same. The `oshi.windows.versions.properties` file is not being found on the classpath, or there are multiple versions with that name and one is being selected which is missing the line:
```
6.3=Server 2012 R2
```
The failure to load that file should show up in your logs, as
```
LOG.warn("Failed to load default configuration");
```
With possibly one of the additional:
```
LOG.info("No {} file found from ClassLoader {}", propsFilename, loader);
```
or
```
LOG.warn("Configuration conflict: there is more than one {} file on the classpath", propsFilename);
```

Which of these log warnings do you see?

**Comment by Anonymenus** [comment] 2021-02-07 07:00
there no loggings only the result. And I found not only server 2012 R2 ,but also windows 10 system ,the result is not different between 5.2.0 and 5.2.1. The  version of 5.2.0 result is 10, as 5.2.1 result is 10.0

**Comment by Anonymenus** [comment] 2021-02-07 07:08
<img width="676" alt="屏幕快照 2021-02-07 下午3 02 20" src="https://user-images.githubusercontent.com/19319821/107139471-550dbe00-6956-11eb-9098-0fea85ac27fc.png">
<img width="618" alt="屏幕快照 2021-02-07 下午3 01 59" src="https://user-images.githubusercontent.com/19319821/107139475-5ccd6280-6956-11eb-857b-5e4a58443375.png">

**Comment by dbwiddis** [comment] 2021-02-07 14:21
This still points to the same properties file and is somehow associated with your setup/class path.

1. The version number resulting in the difference indicates that #1288 is the change resulting in different results.
2. That change introduced a new properties file for matching up Windows versions, [`oshi.windows.versions.properties`](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/resources/oshi.windows.versions.properties)
3. The relevant property values for the two cases you report are present in the file:
```
10.0.nt=10
10.0.17763+=Server 2019
10.0=Server 2016
6.3.nt=8.1
6.3=Server 2012 R2
```
4. The new code works successfully on every system I've tried including test VMs
5. Your output indicates it's returning the default version and is failing on [this line](https://github.com/oshi/oshi/blob/83ed30b12dd69871664f77ebe2f9635fb7b081c4/oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java#L184):
```
Properties verProps = FileUtil.readPropertiesFromFilename("oshi.windows.versions.properties");
version = verProps.getProperty(verLookup.toString()) != null ? verProps.getProperty(verLookup.toString())
```

I have confirmed that the `oshi.windows.versions.properties` is present in the JAR files on maven.  It's in the `src/main/resources` folder if you fork the source, which should be on your classpath by default if you use Maven.  If you are using an IDE that is not well integrated with Maven, you may need to add that as a source folder.

**Comment by dbwiddis** [comment] 2021-02-14 18:19
@Anonymenus have you resolved this problem?

**Comment by Anonymenus** [comment] 2021-02-19 06:42
<img width="820" alt="屏幕快照 2021-02-19 下午2 40 45" src="https://user-images.githubusercontent.com/19319821/108467686-98eeb480-72c0-11eb-8cc3-07fbdab3ccea.png">
<img width="522" alt="屏幕快照 2021-02-19 下午2 41 08" src="https://user-images.githubusercontent.com/19319821/108467693-9a1fe180-72c0-11eb-8afe-5f03f5f2e9f4.png">
I don't know if this is normal, the verLookup value is '.1'

**Comment by dbwiddis** [comment] 2021-02-19 06:52
> the verLookup value is '.1'

I don't see how that is possible.  It is created with:
```
StringBuilder verLookup = new StringBuilder(major).append('.').append(minor);
```
And `major` is an `int` so is impossible to be "empty".

Can you show your complete code starting from the assignment of `verLookup`?

**Comment by dbwiddis** [comment] 2021-02-19 06:58
Or.... DUH. [`new StringBuilder(int)`](https://docs.oracle.com/javase/7/docs/api/java/lang/StringBuilder.html#StringBuilder(int)) defines a capacity.

So how did this ever work?

**Comment by dbwiddis** [comment] 2021-02-19 07:04
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

In the  `WindowsOperatingSystem` class, `parseVersions` method, a `StringBuilder` is instantiated with an integer meant to be part of the string, but is used as a capacity instead.  This prevents the code from properly calculating major.minor version numbers.

### What to do 

In [WindowsOperatingSystem](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java#L168) line 168, replace `new StringBuilder(major)...` with `new StringBuilder().append(major)...`

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

**Closed** 2021-02-21 03:01 UTC
Labels: PR welcome, confirmed bug, first-timers-only, good first issue, up for grabs
