### ISSUE TITLE
Methods that return Total/Used/Free space, all return 0 bytes

### ISSUE THREAD

**Issue by igorbajatovski** [oshi/oshi#1558] opened 2021-03-07 16:48 UTC
I have CentOS 5.5 machine that uses Volume Groups/Logical volumes and when I try to retrieve Total/Used/Free space for all drives, it returns 0 bytes for all of them. This is the output of my disk and my Test java application:

```
[oracle@centos5]$ df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup00-LogVol00
                      442G  301G  119G  72% /
/dev/sda1             110M   16M   88M  16% /boot
tmpfs                 4.0G  2.1G  1.9G  52% /dev/shm
```
[oracle@centos5]$ /usr/java/jdk1.8.0_231/bin/java -jar Test.jar
##########################################################################
Mount:/boot
Name:/dev/sda1
Label:/dev/sda1
Logical volume:
Volume:/dev/sda1
Used space:0
Free space:0
Total space:0
##########################################################################
##########################################################################
Mount:/
Name:/dev/root
Label:/dev/root
Logical volume:
Volume:/
Used space:0
Free space:0
Total space:0
##########################################################################
##########################################################################
Mount:/
Name:rootfs
Label:rootfs
Logical volume:
Volume:/
Used space:0
Free space:0
Total space:0
##########################################################################

**Comment by dbwiddis** [comment] 2021-03-07 17:00
Are there any log warnings associated with this?  OSHI gets the file sizes by calling `statvfs()`.

@tausiflife would you be able to look into this? You know more about logical volumes than I do.

One potential fix is to check whether total size is 0 after the initial statvfs call and use the JDK backup methods in that case.

**Comment by igorbajatovski** [comment] 2021-03-07 17:48
Here is the output of my Test java application with log info:

[oracle@centos5 maksystem]$ /usr/java/jdk1.8.0_231/bin/java -jar Test.jar
**File not found or not readable: /etc/os-release
Failed to get file counts from statvfs. /home/oracle/.cache/JNA/temp/jna4654330232156976794.tmp: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /home/oracle/.cache/JNA/temp/jna4654330232156976794.tmp)
Failed to get file counts from statvfs. Could not initialize class com.sun.jna.Native
Failed to get file counts from statvfs. Could not initialize class com.sun.jna.Native**
##########################################################################
Mount:/boot
Name:/dev/sda1
Label:/dev/sda1
Logical volume:
Volume:/dev/sda1
Used space:0
Free space:0
Total space:0
##########################################################################
##########################################################################
Mount:/
Name:/dev/root
Label:/dev/root
Logical volume:
Volume:/
Used space:0
Free space:0
Total space:0
##########################################################################
##########################################################################
Mount:/
Name:rootfs
Label:rootfs
Logical volume:
Volume:/
Used space:0
Free space:0
Total space:0
##########################################################################

**Comment by dbwiddis** [comment] 2021-03-07 18:04
What version of glibc do you have? That seems to be the root cause.

**Comment by mprins** [comment] 2021-03-07 18:09
> Failed to get file counts from statvfs. /home/oracle/.cache/JNA/temp/jna4654330232156976794.tmp: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /home/oracle/.cache/JNA/temp/jna4654330232156976794.tmp)

this seems pretty clear; 
> I have CentOS 5.5 machine 

Your OS was released over a decade ago and retired several years ago, it is missing an up to date version core library that the current version of JNA depends on. 

You could try to build a matching version of libc on your system to work around that or perhaps try with a really old version of JNA

**Comment by igorbajatovski** [comment] 2021-03-07 18:12
GNU C Library stable release version 2.5, by Roland McGrath et al.
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.1.2 20080704 (Red Hat 4.1.2-55).
Compiled on a Linux 2.6.9 system on 2015-01-27.
Available extensions:
        The C stubs add-on version 2.1.2.
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        GNU libio by Per Bothner
        NIS(YP)/NIS+ NSS modules 0.19 by Thorsten Kukuk
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
        RT using linux kernel aio
Thread-local storage support included.
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.

**Comment by dbwiddis** [comment] 2021-03-07 18:27
As @mprins said you have a very old and probably unsupported OS.  

An older version of JNA and OSHI might work but not have the same features you want.  Upgrading your OS version is probably the easiest path forward.

**Comment by dbwiddis** [comment] 2021-03-07 22:05
See this issue at the JNA project.  You may be able to rebuild JNA on your own system with the older glibc.
https://github.com/java-native-access/jna/issues/771

Other than that, I don't think there's much we can do on the OSHI side, so I'm closing this.

**Closed by dbwiddis** 2021-03-07 22:05 UTC
Labels: compatibility, external dependency

**Comment by dbwiddis** [comment] 2021-03-07 23:38
I improved the fallback logic to fix this particular issue but there are many other problems you will have with native methods on Linux using the older distro.   See @Space2Man comments on #1274 with similar issue.

**Comment by tausiflife** [comment] 2021-03-08 06:37
> Are there any log warnings associated with this?  OSHI gets the file sizes by calling `statvfs()`.
> 
> 
> 
> @tausiflife would you be able to look into this? You know more about logical volumes than I do.
> 
> 
> 
> One potential fix is to check whether total size is 0 after the initial statvfs call and use the JDK backup methods in that case.

By the time i see some issue, they are closed. Will try to catch up next time.

**Comment by dbwiddis** [comment] 2021-03-08 06:40
No worries, @tausiflife -- originally I thought it was related to the logical volumes and you're my go-to expert on that :)
