### ISSUE TITLE
SystemCpuLoadTicks all 0's on Windows OS from oshi-core-5.3.5 onwards

### ISSUE THREAD

**Issue by NCC1031A** [oshi/oshi#2694] opened 2024-07-31 08:07 UTC
Hi,
   Application runs on Windows OS as a service. Service "Log On As" user can be part of Administrator group or non-admin.
Upgraded oshi-core from 5.2.4 to 6.4.0. This stopped SystemInfo().getHardware().getProcessor().getSystemCpuLoadTicks() fetching CPU ticks for non-admin service users. Returns an empty array with all values zero. 

We can't go back to 5.2.4 as it creates issue in Apple M1 and higher machines.
Version 5.3.4 and below fetches CPU ticks for all users. Version 5.3.5 and higher returning empty array for non-admin service user. Tested on Windows 2019, 2016 and 2012. Not tried 2022 or other windows versions.

Found #1400 is the root case which makes Windows System CPU usage Process-group aware.
To remediate this issue, solution we found is to add non-admin service user to Windows "Performance Monitor Users" group.
If hundreds of applications are installed on equal number of machines, this is causing additional headache to add user in each machine to "Performance Monitor Users" group. 

We would like to know
1. What is Windows System CPU usage Process-group aware mean or the requirement behind it?
2. What are different ways provided by oshi-core-6.4.0 or higher version to access CPU ticks by non-admin service users?
3. Can we circumvent #1400 or is there any other way a non-admin service user can access System CPU Load Ticks like in oshi-core-5.3.4 or earlier versions?

**Comment by dbwiddis** [comment] 2024-08-03 05:54
Hey @NCC1031A ... sorry you're having troubles here.  I hope we can get to the bottom of this.

> What is Windows System CPU usage Process-group aware mean or the requirement behind it?

The PR was to fix a bug reported in #1373.  When a Windows system has more than 64 logical processors, they are split into multiple processor groups.  Various Windows APIs only show "half" of the statistics available.

Prior to #1400 we had used the WMI table / PDH counters for the "Processor" group.  This was one particular API that would only give results for the current processor group.   However, the "ProcessorInformation" WMI table / PDH counters do track processor groups.

Unfortunately their "total" calculation in that table isn't useful, so #1400 just reverted to "let's calculate the per-processor ticks and add them up".

> What are different ways provided by oshi-core-6.4.0 or higher version to access CPU ticks by non-admin service users?

OSHI uses three sources for the tick data, and none have normally required admin permissions:
1. Directly from the registry under the HKEY_PERFORMANCE_DATA.   The docs say to prefer the PerfMon API to this, but they draw their data ultimately from the same source and the registry is faster. This registry option can be disabled in the config.
2. Performance Counter API.  Accesses the same data you'd see running `perfmon.exe`.  This is the default if the registry option is disabled.
3. WMI.  There are WMI tables corresponding to each of the performance counters.  It's the slowest because of the COM overhead, but also the most robust to internationalization.  If perfmon counters get errors, WMI is used as a backup.

> Can we circumvent https://github.com/oshi/oshi/pull/1400 or is there any other way a non-admin service user can access System CPU Load Ticks like in oshi-core-5.3.4 or earlier versions?

You could certainly write the same code yourself that was removed in #1400.  That uses [this WMI table](https://wutils.com/wmi/root/cimv2/win32_perfrawdata_perfos_processor/) or its performance counter equivalents.

NOTE:

The interesting thing here is that all that PR change really did was switch to adding up per-processor counts. And it turns out they were broken by a malformed WMI string -- which means they worked in registry and perfmon settings but failed in the direct WMI query.  So if you're just looking at #1400 and 5.3.5 you may have missed that that bug was fixed in #1562, which was version 5.6.2 and/or 6.1.0.

But as you say your issue exists on 6.4.0.

So my suggestions for further debugging:

1. Disable the registry fetch of counters. It's possible that's what's giving you the 0's.  You'd set this config to false:
https://github.com/oshi/oshi/blob/1d251ced0f2e2c0c3ce5384d2e8df70b1afc178a/oshi-core/src/main/java/oshi/util/GlobalConfig.java#L42

2. Investigate to see if you can see the per-processor counters.

3. Investigate whether perfmon.exe or WMI tables (wmic command line or Get-WmiObject powershell) gives you that data.

**Comment by NCC1031A** [comment] 2024-08-05 13:17
Hi @dbwiddis,
   How to set "oshi.os.windows.hkeyperfdata=false" in [oshi-core/src/main/resources/oshi.properties](https://github.com/oshi/oshi/blob/1d251ced0f2e2c0c3ce5384d2e8df70b1afc178a/oshi-core/src/main/resources/oshi.properties#L77)? 
   Application uses oshi-core-6.4.0 jar from maven repo without modification.

**Comment by dbwiddis** [comment] 2024-08-06 07:04
> Hi @dbwiddis, How to set "oshi.os.windows.hkeyperfdata=false" in [oshi-core/src/main/resources/oshi.properties](https://github.com/oshi/oshi/blob/1d251ced0f2e2c0c3ce5384d2e8df70b1afc178a/oshi-core/src/main/resources/oshi.properties#L77)? Application uses oshi-core-6.4.0 jar from maven repo without modification.

You can use `GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_HKEYPERFDATA, false);` when you first start up the application. The config is not thread safe and changed configs aren't guaranteed to be reread during operation, so ideally you do this before you even instantiate `SystemInfo` or very shortly thereafter.

**Comment by NCC1031A** [comment] 2024-08-07 12:45
Hi @dbwiddis,
 After using `GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_HKEYPERFDATA, false);` I am still getting all ticks as 0s.
> ticks: [0, 0, 0, 0, 0, 0, 0, 0]

Logs print GlobalConfig.OSHI_OS_WINDOWS_HKEYPERFDATA=false after setting.
I can get ticks by adding non-admin service user to Windows "Performance Monitor Users" group or #1400 removed code.

**Comment by dbwiddis** [comment] 2024-08-07 15:58
Hey @NCC1031A thanks for your patience in debugging.   Let me summarize what we know:

1. In [this comment](https://github.com/oshi/oshi/issues/2694#issuecomment-2266427480) I noted the three data sources and their precedence: registry first (unless disabled), then PDH, then WMI.  
2. The fact that you were able to bisect the problem to #1400 shows that you were already failing on the first two options and resorting to WMI.
3. Due to another bug in the WMI Query string at the time #1400 went in, it didn't work but that string should have been fixed and the issue fixed in 6.1.0.  Since you indicate the problem still exists in 6.4.0 then either that fix didn't work or there's another problem.

I'm not that familiar with service users or their permissions, but it does seem there are some restrictions which is why we're defaulting back to WMI here; [this post](https://forum.newrelic.com/s/hubtopic/aAX8W0000008aheWAA/relic-solution-insufficient-permission-to-collect-windows-performance-counters) for a different product probably indicates why the registry and PDF approaches don't work:
> If you want to access those metrics, you’ll need to grant your IIS user access to the performance counter data in Windows.
>
> For .NET Framework applications, the Windows User under which your application runs must have access to Windows performance counter data. Usually this is accomplished by adding the user to "Performance Monitor Users" and "Performance Log Users" groups. Insufficient permissions will result in the agent not collecting garbage collection metrics.

This seems to align exactly with the solution you already have.

So we're back to using WMI as a backup, and the table involved ([Win32_PerfRawData_Counters_ProcessorInformation](https://wutils.com/wmi/root/cimv2/win32_perfrawdata_counters_processorinformation/)).  Would you be able to execute the command line version of the WMI Queries (`wmic`) or Powershell `Get-WMI-Object` from your service user to investigate?

This should be the equivalent of the per-ticks query
```cmd
wmic path Win32_PerfRawData_Counters_ProcessorInformation where "NOT Name LIKE '%\_Total'" get /format:list
```
or in powershell
```powershell
Get-WmiObject -Query "SELECT * FROM Win32_PerfRawData_Counters_ProcessorInformation WHERE NOT Name LIKE '%\_Total'"
```
The code removed in #1400 used the `%_Total` result from that query, so also try to see if it's different with or without that removal. 

There's also another table with system level counters, [Win32_PerfRawData_PerfOS_Processor](https://wutils.com/wmi/root/cimv2/win32_perfrawdata_perfos_processor/) that was removed in #1400.  Running similar queries against that table would be helpful.

**Comment by NCC1031A** [comment] 2024-08-12 13:17
Hi @dbwiddis,
    I am able to run both queries on command and powershell prompt with a small change. I removed '\' from both queries to avoid syntax error. Opened both prompts by right clicking and "Run as as different user" and providing non-admin user credentials in popup. 

I will recommend our customers to add the user to "Performance Monitor Users" or "Performance Log Users" group when Windows host logical processor greater than 64. For <=64, I will use the removed code from #1400.

**Comment by dbwiddis** [comment] 2024-08-12 15:00
> I am able to run both queries on command and powershell prompt with a small change.

Thanks for confirming this.  

I'm guessing the WQL query is still wrong in some way.  Unfortunately I don't have Windows hardware any more to test out any fix.  But this is likely a fixable bug.

> I will recommend our customers to add the user to "Performance Monitor Users" or "Performance Log Users" group when Windows host logical processor greater than 64. For <=64, I will use the removed code from #1400.

This is a good workaround for now; but I would like to get this bug fixed.

**Comment by NCC1031A** [comment] 2024-08-14 05:09
Hi @dbwiddis,
   Is there a ETA when this bug will get fixed?
If the fix is coming within next 1 month (by Sep-30), then I would like to wait for the release of oshi-core-6.x version which has the fix.

**Comment by dbwiddis** [comment] 2024-08-14 05:47
I'll try to further investigate if it's fixable within the next week.  If so I'll fix it and promptly cut a new release.  If not, I'll let you know.

I don't have a personal windows machine so I'll be relying on GitHub CI logs.

**Comment by NCC1031A** [comment] 2024-08-14 06:31
Hi @dbwiddis,
I will help you validating new release with fix. Please, let me know if it is fixable or not once you are done and a new release version.

**Comment by dbwiddis** [comment] 2024-08-15 16:13
@NCC1031A I've done enough testing to confirm that the existing code _should_ work.   I don't know why it doesn't work on your machines.

I will go ahead and add back the removed code from #1400 as an opt-in configuration choice for this edge case.  Expect a new version over the coming weekend.

**Comment by dbwiddis** [comment] 2024-08-17 07:52
@NCC1031A I've merged #2705. The new code should be available in the snapshot.

You can enable the old (pre-#1400) calculation by setting the config `oshi.os.windows.legacy.system.counters` to `true`, for example set this on startup (before instantiating the CentralProcessor):
```java
GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_LEGACY_SYSTEM_COUNTERS, true); 
```

Can you test this out before I cut a release?

**Comment by NCC1031A** [comment] 2024-08-19 13:57
Hi @dbwiddis,
How can I download the oshi-core-*-snapshot.jar for windows? Is there a maven dependency for snapshot that contains #2705?

**Comment by dbwiddis** [comment] 2024-08-19 14:20
There's a link on the README under downloads: https://github.com/oshi/oshi?tab=readme-ov-file#downloads-and-dependency-management

It's the standard Maven snapshot repo.   Yes it has #2705, it gets [auto-published](https://github.com/oshi/oshi/actions/workflows/sonatype.yaml) when a PR is merged.

**Comment by NCC1031A** [comment] 2024-08-20 08:21
I am able to get CPU ticks by setting the legacy counter to true. Thank you for making the changes.

`GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_LEGACY_SYSTEM_COUNTERS, true); `

**Comment by dbwiddis** [comment] 2024-08-20 08:23
I'll cut a release shortly.

**Comment by NCC1031A** [comment] 2024-09-06 10:11
Hi @dbwiddis,
   After using oshi-core-6.6.3.jar, application is not starting with exception. Application starts if I revert back to oshi-core-6.4.0. Attached "oshi-core-6.6.3_error_on_Apple_M2.log". Java version openjdk 17.0.12. Machine is Apple MacBook Pro 2023 M2 chip. Let me know if you would like to address this as a new defect.

[oshi-core-6.6.3_error_on_Apple_M2.log](https://github.com/user-attachments/files/16906272/oshi-core-6.6.3_error_on_Apple_M2.log)

**Comment by dbwiddis** [comment] 2024-09-06 15:20
This probably should have been posted on a new issue; commenting on closed issues is easy to miss.

That said, the stack trace only shows the JNA portions of it.  Is there any OSHI method call in the stack trace?

The problem is that it's trying to load the (Windows) Kernel32.dll on a mac system.  This would only happen if it failed to properly detect the operating system, which is done in the JNA `Platform` class based on matching this:
```
String osName = System.getProperty("os.name");
...
        else if (osName.startsWith("Windows")) {
            osType = WINDOWS;
        }
```
> Let me know if you would like to address this as a new defect.

Lacking any stack trace showing OSHI miscalculating the platform result, I don't even know how you get here.

If `os.name` is incorrect, there's really not much we can do since [even the JDK relies on this property](https://github.com/openjdk/jdk/blob/5b72bbf9d4a4c9c966a665c8d48e5f6c0dcdba1c/src/jdk.internal.le/share/classes/jdk/internal/org/jline/utils/OSUtils.java#L18-L19).

Can you point to where OSHI or JNA is doing something wrong here?  A longer stack trace excerpt would help.

**Comment by dbwiddis** [comment] 2024-09-06 15:32
Looks like the problem is in this library.
```
	at com.sun.jna.platform.win32.Kernel32.<clinit>(Kernel32.java:44)
	at com.sun.jna.platform.win32.Advapi32Util.getCurrentUserGroups(Advapi32Util.java:559)
	at com.service_now.monitor.StatusMonitor$Collector.isPerformanceUser(StatusMonitor.java:350)
	at com.service_now.monitor.StatusMonitor$Collector.<init>(StatusMonitor.java:293)
	at com.service_now.monitor.StatusMonitor.postStart(StatusMonitor.java:128)
	at com.snc.midserver.monitor.internal.MonitorRunner.start(MonitorRunner.java:83)
	at com.snc.midserver.monitor.internal.Monitors.startMonitor(Monitors.java:371)
	at com.snc.midserver.monitor.internal.Monitors.addMonitor(Monitors.java:353)
	at com.snc.midserver.monitor.internal.Monitors.lambda$start$0(Monitors.java:117)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:297)
	at com.snc.midserver.monitor.internal.Monitors.start(Monitors.java:115)
	at com.snc.midserver.monitor.internal.Monitors.onMIDServerEvent(Monitors.java:508)
	at com.service_now.mid.services.Events.internalFire(Events.java:119)
	at com.service_now.mid.services.Events.fire(Events.java:42)
	at com.service_now.mid.services.StartupSequencer.startServices(StartupSequencer.java:444)
	at com.service_now.mid.services.StartupSequencer.testsSucceeded(StartupSequencer.java:218)
	at com.service_now.mid.services.StartupSequencer.startupSequencerRunnable(StartupSequencer.java:723)
```
The servicenow MID website indicates [they only have downloads for Linux and WIndows](https://docs.servicenow.com/bundle/vancouver-servicenow-platform/page/product/mid-server/concept/mid-server-installation.html).  Apparently you can install on a mac by using the linux zip file:  https://blog.yansalabs.com/2023/11/13/installing-a-mid-server-on-a-mac/ but perhaps a Windows zip was used?

In any case, I can't see how this has anything at all to do with OSHI, other than the transitive dependency on JNA which may be a different version, but in any case, shouldn't be called.

**Comment by dbwiddis** [comment] 2024-09-07 07:19
RE-closing this as all evidence points to a file which doesn't do any checking of the platform being used to access JNA. If you still feel there's an issue in OSHI, please open a new issue to discuss.

**Closed by dbwiddis** 2024-09-07 07:19 UTC
Labels: bug?, compatibility
