### ISSUE TITLE
Detecting the graphics specs.

### ISSUE THREAD

**Issue by ravimohan1991** [oshi/oshi#753] opened 2019-01-09 18:44 UTC
I was wondering if the routines generating the information related to Graphic card can be written in these libraries.

**Comment by dbwiddis** [comment] 2019-01-09 20:31
We could probably do something similar to the Sound Card feature, for the Video Card.  Feel free to contribute a PR.

**Comment by cilki** [comment] 2019-01-09 21:16
Duplicate of #400.

**Comment by dbwiddis** [comment] 2019-01-09 23:16
Good point. I'll close this and we can continue any discussion on #400.

**Closed by dbwiddis** 2019-01-09 23:16 UTC
Labels: PR welcome, new feature
