### ISSUE TITLE
Get details of the current process

### ISSUE THREAD

**Issue by romil-patel** [oshi/oshi#1323] opened 2020-08-24 12:17 UTC
I am using _oshi-core_ with _JDK 11_ with the following code to get the details about the current process but unable to get the details as it always returns 0.

```
OperatingSystem os = si.getOperatingSystem();
os.getProcess(os.getProcessId()).getResidentSetSize() //gives 0
```

I have gone through the [ProcessPanel](https://github.com/oshi/oshi/blob/master/oshi-demo/src/main/java/oshi/demo/gui/ProcessPanel.java) from OshiGUI in which I can see the details of my required process. But when I use the same code with the function I am unable to get current the process details.

        OperatingSystem os = si.getOperatingSystem();
        List<OSProcess> processes = Arrays.asList(os.getProcesses(0, null));  
        processes.indexOf(os.getProcessId()); //gives -1

```
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>5.2.4</version>
        </dependency>
```

I have one task created which triggers at every 5 seconds and collect the usage details as follows. 

**OS Details:**
Windows 10 Pro
System type: 64-bit, x64 based processor
Processor: Intel(R) Core(TM) i3-3210

```
public class StatsUtils {

    private SystemInfo si = new SystemInfo();

    public void getProcessUsage() {

        OperatingSystem os = si.getOperatingSystem();
        final int pid = os.getProcessId();
        List<OSProcess> processes = Arrays.asList(os.getProcesses(0, null));

        Optional<OSProcess> process = processes.stream().filter(p -> p.getProcessID() == pid).findFirst();
        log.info("process 1: {}", process.isPresent());

        Map<Integer, OSProcess> procMap = new HashMap<>();
        processes.stream().forEach(p -> procMap.put(p.getProcessID(), p));
        process = Optional.ofNullable(procMap.get(os.getProcessId()));
        log.info("process 2: {}", process.isPresent());

    }

}
```
**Output:**
```

process 1: false
process 2: false
```

```
public class TaskCollectStats extends TimerTask {

    StatsUtils statsUtils = new StatsUtils();

    public TaskCollectStats() { }

    @Override
    public void run() {
        statsUtils.getProcessUsage();        
        //other code
    }

}
```

**Comment by dbwiddis** [comment] 2020-08-24 15:11
`os.getProcess(os.getProcessId()).getResidentSetSize()` should give you a nonzero result.  To help you troubleshoot, I need to know what operating system you are using.

**Comment by romil-patel** [comment] 2020-08-24 15:38
@dbwiddis Thanks for the reply. I have tried the solution shared but unfortunately, it is not working. I have added the OS details and related code.

**Comment by dbwiddis** [comment] 2020-08-24 15:51
Can you please try the previous version of OSHI, 5.2.3?  I wonder if #1320 broke something.

**Comment by dbwiddis** [comment] 2020-08-24 15:56
How does `Arrays.asList(os.getProcesses(0, null));` worok?  Isn't `os.getProcesses()` already returning a list?  That shouldn't even compile on version 5.x.

**Comment by romil-patel** [comment] 2020-08-24 16:12
I have tried with OSHI 5.2.3 but I am getting the same result as above.  _os.getProcesses_ has  `OSProcess[] getProcesses(int var1, OperatingSystem.ProcessSort var2);`

**Comment by romil-patel** [comment] 2020-08-24 16:20
However, I am able to get the other processes and their details but facing issue with the current process

**Comment by dbwiddis** [comment] 2020-08-24 17:07
The `OSProcess[]` return type is from OSHI 4.X and previous.  So you may have an older version of the JAR in your project somewhere if you're seeing that.

**Comment by dbwiddis** [comment] 2020-08-26 01:01
Haven't heard an update.  Were you able to resolve the problem?

**Comment by romil-patel** [comment] 2020-08-26 04:25
Thanks, @dbwiddis, for the quick reply and help, yes you were correct, there was OSHI 4.x in the classpath, I have removed and clean the project and It's working fine and I am able to get the details for the current process

**Comment by romil-patel** [comment] 2020-08-26 04:26
Can you please guild on ` process.getThreadDetails()` which gives `[]` where the process is the current process.

**Comment by dbwiddis** [comment] 2020-08-26 05:16
The `[]` implies array (4.X) vs. List (5.X) for thread details?

**Comment by romil-patel** [comment] 2020-08-26 05:18
It is a list 5.X. List<OSThread> getThreadDetails();

**Comment by dbwiddis** [comment] 2020-08-26 05:33
It can return empty if it fails to return thread information from the performance counters.  Are you able to see the current process threads in `perfmon.exe`?

**Comment by dbwiddis** [comment] 2020-08-26 18:19
You'll have to provide me more information if you need more debugging help.  I can't reproduce the problem you report.

```
public static void main(String[] args) {
        SystemInfo si = new SystemInfo();
        OperatingSystem os = si.getOperatingSystem();
        System.out.println(os.toString());

        int pid = os.getProcessId();
        OSProcess proc = os.getProcess(pid);
        int threadCount = proc.getThreadCount();
        List<OSThread> threads = proc.getThreadDetails();
        System.out.println("Running " + threadCount + " threads. List of details for " + threads.size() + " threads.");
        for (OSThread thread : threads) {
            System.out.println(thread.toString());
        }
}
```

Output:
```
Microsoft Windows 10.0 build 18362
Running 27 threads. List of details for 27 threads.
OSThread [threadId=22976, owningProcessId=16964, name=javaw/2, state=SLEEPING, kernelTime=0, userTime=0, upTime=6204, startTime=1598465816126, startMemoryAddress=0xed38ce30, contextSwitches=27, minorFaults=0, majorFaults=0]
OSThread [threadId=4864, owningProcessId=16964, name=javaw/5, state=SLEEPING, kernelTime=0, userTime=0, upTime=6180, startTime=1598465816150, startMemoryAddress=0xed38ce30, contextSwitches=47, minorFaults=0, majorFaults=0]
OSThread [threadId=22852, owningProcessId=16964, name=javaw/14, state=SLEEPING, kernelTime=0, userTime=15, upTime=6164, startTime=1598465816166, startMemoryAddress=0xed38ce30, contextSwitches=4, minorFaults=0, majorFaults=0]
... <27 total lines> ...
```

**Comment by romil-patel** [comment] 2020-08-27 16:19
I have tried with the same again and it is working fine, there might be some issue with the performance counter. Thanks for the quick reply and guide that you have provided.

**Comment by dbwiddis** [comment] 2020-08-27 17:04
OK, I'll close this as it appears resolved.

**Closed by dbwiddis** 2020-08-27 17:04 UTC
