### ISSUE TITLE
ProcessorIdentifier.cpuVendor is null

### ISSUE THREAD

**Issue by lcfliuxi** [oshi/oshi#2703] opened 2024-08-15 09:09 UTC
![1](https://files.catbox.moe/d00joi.png)
![2](https://files.catbox.moe/v15sch.png)
![3](https://files.catbox.moe/oyf6jy.png)

**Comment by lcfliuxi** [comment] 2024-08-15 09:10
![4](https://github.com/user-attachments/assets/8235f536-6089-4914-9691-58d666dc28ec)

**Comment by dbwiddis** [comment] 2024-08-15 15:44
Looks like a duplicate of #2513 fixed by #2514 in [6.4.8](https://github.com/oshi/oshi/releases/tag/oshi-parent-6.4.8).

Your screenshot shows you are running 6.4.7.

![Screenshot 2024-08-15 at 8 43 55 AM](https://github.com/user-attachments/assets/3f1d00db-08ec-46cb-873f-354c3ff27df8)

**Comment by lcfliuxi** [comment] 2024-08-16 02:32
Thank you, I get it, this is a bug in 6.4.7, because this.cpuVendor is still null.
the follow code is in 6.4.7.
private String queryVendorFromImplementer() {
            Properties archProps = FileUtil.readPropertiesFromFilename(OSHI_ARCHITECTURE_PROPERTIES);
            String vendor = archProps.getProperty("hw_impl." + this.cpuVendor);
            return (vendor == null ? this.cpuVendor : vendor);
        }

the follow code is in 6.4.8.
private String queryVendorFromImplementer(String cpuVendor) {
            Properties archProps = FileUtil.readPropertiesFromFilename(OSHI_ARCHITECTURE_PROPERTIES);
            String vendor = archProps.getProperty("hw_impl." + this.cpuVendor);
            return (vendor == null ? cpuVendor : vendor);
        }

I’m confused, isn’t this.cpuVendor still null here?
String vendor = archProps.getProperty("hw_impl." + this.cpuVendor);

May be it got archProps.getProperty("hw_impl.null");
So vendor is still null, though oshi.architecture.properties has defined.

The right code may be
private String queryVendorFromImplementer(String cpuVendor) {
            Properties archProps = FileUtil.readPropertiesFromFilename(OSHI_ARCHITECTURE_PROPERTIES);
            String vendor = archProps.getProperty("hw_impl." + cpuVendor);
            return (vendor == null ? cpuVendor : vendor);
        }

**Comment by lcfliuxi** [comment] 2024-08-16 02:45
I verified that my cpuVendor is 0x70, but the final result is still 0x70. It should actually be Phytium.

**Comment by dbwiddis** [comment] 2024-08-16 03:54
> The right code may be
> 
> ```
> private String queryVendorFromImplementer(String cpuVendor) {
>     Properties archProps = FileUtil.readPropertiesFromFilename(OSHI_ARCHITECTURE_PROPERTIES);
>     String vendor = archProps.getProperty("hw_impl." + cpuVendor);
>     return (vendor == null ? cpuVendor : vendor);
> }
> ```

Yep, you're right.  

I'll get a fix out this weekend.

**Comment by lcfliuxi** [comment] 2024-08-16 05:17
Alright, thank you.

**Closed** 2024-08-16 06:09 UTC
Labels: confirmed bug
