### ISSUE TITLE
Failed to add PDH Counter:

### ISSUE THREAD

**Issue by spyhunter99** [oshi/oshi#662] opened 2018-10-23 07:10 UTC
on v3.9.1, i'm seeing the following in the log output. I'm not sure if this is a problem but it appears to be happening randomly, although infrequently. It's on an older machine win7x64. I'm not using either of those counters (that i know of)

02:56:38,372 WARN  [windows.PerfDataUtil] Failed to add PDH Counter: \Process(_Total)\Handle Count, Error code: 0xC0000BB8
02:56:38,380 WARN  [windows.PerfDataUtil] Failed to add PDH Counter: \System\Context Switches/sec, Error code: 0xC0000BB8
02:56:38,380 WARN  [windows.WindowsCentralProcessor] Unable to enumerate performance counter instances for .

**Comment by dbwiddis** [comment] 2018-10-23 07:37
OSHI makes the assumption when you try to add a counter that it's bad, and it doesn't try to add it again.  You can remove and re-add the problematic counters when this happens.

I'm not surprised that an older version of windows might not have some counters, but it's odd that they would fail after some period of working properly.  I wonder if it involves a network interface shutting down or a disk sleeping.  If you can give me the log messages around when those issues start I can try to stop the repeats.  Or you can try to detect the problematic output yourself (probably 0's) and try to remove/re-add the counters using the PerfDataUtil.

**Comment by dbwiddis** [comment] 2018-10-23 07:37
The 0xC0000BB8 error may be permissions based, by the way.

**Comment by spyhunter99** [comment] 2018-10-23 07:49
The 0xC0000BBC error was actually on modern hardware, win7 enterprise, patched x64. Is it possible there's a resource leak? I'll look into hooking into the logging subsystem to capture the error state there and force the process to restart in the mean time

**Comment by dbwiddis** [comment] 2018-10-23 15:28
Right, the initial BB8 error was permissions based.  R2D2 has better access. ;)

The BBC error may be a resource leak but I'd need more info to try to narrow down where.   

You shouldn't need to hook into logs, just read the counter results... counters should be monotonically increasing (or at least nondecreasing) so if the counter goes down (or to 0, the default) that's a clear sign it's not working and can be removed/re-added.  (That's something you'd have to modify/extend OSHI's class to do, though, it's not set up to easily "reset" a counter.... possibly functionality that should be added.)

**Comment by dbwiddis** [comment] 2018-10-26 01:31
I've committed #666 that tries to detect that BBC error and remove/re-add the counter when it occurs.  Can you test it out?

**Comment by dbwiddis** [comment] 2018-10-30 21:34
Any update on testing?

**Comment by spyhunter99** [comment] 2018-11-11 06:45
i was unable to reproduce on my dev machine for both head and the latest, so it may have been an environment thing. i guess we can close now and reopen if it comes back. thanks!

**Comment by spyhunter99** [comment] 2018-11-27 14:42
I'm seeing this again with 3.10.0. Other than spamming the logs, i see other ill effects. Should I just ignore this? Here's the error message (running as a regular user and as admin)

    WARN [windows.PerfDataUtil] Failed to get counter: Error code: 0xC0000BBC

**Comment by dbwiddis** [comment] 2018-11-27 15:02
Which counter is producing the error?  Did it work once and stop working?

**Comment by spyhunter99** [comment] 2018-11-29 17:42
is there a debug flag or something to that affect that i can set to get more information?

**Comment by dbwiddis** [comment] 2018-11-29 22:32
Unfortunately it looks like I excluded that, but there are only 10 methods that call that, so you can probably narrow it down by what stats you're refreshing on in your client.  Possibilities are:
- Processor (interrupts, context switches, system CPU ticks, processor CPU ticks)
- Sensors (temperature)
- Memory (memory usage, swap)
- FileSystem (open descriptors)
- Disks (reads/writes)

However, I'm surprised that's the only log message you're getting. That log warning is generated on PerfDatautil line 345, and displays the error value 0xC0000BBC (invalid handle).  That method returns that error value as a negative value to the calling method, queryCounter() at line 206. That should go into the conditional at line 207, and then be checked against PDH_INVALID_HANDLE, which is 0xC0000BBC...

Ooooooh, I see the error now!  Dang, that's a sneaky little bug!  (And I found it by explaining it to you and/or a rubber duck.)   OSHI's error value on line 345 (and the return) is a `long`.  0xC0000BBC as a `long` is a positive number.  However, as an `int` (the error constant) it's a negative number.

So the `return -1L * ret;` on line 348 is wrong.  We need to do the bitwise math to only get the least significant 32 bits (which would be a negative number) and return that.

**Comment by dbwiddis** [comment] 2018-11-29 22:45
To be more specific on the bug: the error code is an `int`, where the first bit is signed.  It returns from the method as a `long` which fills the high order bits with 1's instead of 0's.  And it fails the comparison of 0xFFFFFFFFC0000BBC vs. 0xC0000BBC.

There's a correct way to do this that I'm not sure of at the moment.

**Comment by dbwiddis** [comment] 2018-12-01 03:44
All it really took was removing the -1.  I threw in better conditional logic and more logging while I was at it.  Can you test SNAPSHOT?

**Comment by spyhunter99** [comment] 2018-12-01 13:35
i'll give it a shot on monday

**Comment by spyhunter99** [comment] 2018-12-03 15:39
ok just tested off of master as of an hour or so ago. It's running ok, but i have more data in the logs to help you. 
Failed to get counter. Error code: 0xC0000BBC
Removing and re-adding counter: \Memory\Pages Input/sec
Removing and re-adding counter: \Memory\Pages Output/sec

**Comment by spyhunter99** [comment] 2018-12-03 15:52
what's strange is this only seems to happen when i'm actively polling for disk i/o metrics.

**Comment by dbwiddis** [comment] 2018-12-05 07:46
OK, that's the expected result if a counter loses its handle.  But after regenerating a new handle it shouldn't repeat itself, right?

I'm wondering if we have a resource leak in the disk i/o polling. Can you tell me specifically what code you're running often?

**Comment by spyhunter99** [comment] 2018-12-05 20:06
it's possible. it's basically printing out the message every time I make a query. I'll get you some sample code to try and reproduce this to help narrow it down.

**Comment by spyhunter99** [comment] 2018-12-06 21:54
slightly more info for you. the first error message is 

````
failed to update counter error code 0x800007D5
disabling future updates for Memory
````

hope this helps narrow it down. i had a hard time tracking down the root cause of this, but i did succeed. It looks like it has to do with reusing the HAL object and some kind of conflict between getDiskStores() and getMemory() on windows. If I always use new instances of HardwareAbstractionLayer the problem seems to go away.

This should be enough to reproduce it

````
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal= si.getHardware();
while (true) {
hal.getDiskStores();
hal.getMemory().getSwapPagesIn();
}

````

**Comment by spyhunter99** [comment] 2018-12-07 03:58
this was with 3.10.0 by the way

**Comment by dbwiddis** [comment] 2018-12-07 04:31
Are you polling in a loop with no delay?  

The 0x800007d5 error code is PDH_NO_DATA which seems to me to imply you're polling the counter faster than it can respond.  In general I wouldn't expect OSHI to work well polling anything more frequently than 1-second intervals.  And when you're dealing with hardware (disk I/O and swap pages) there may be even more of a delay or hardware limit depending on the disk driver.

**Comment by spyhunter99** [comment] 2018-12-07 13:37
still seeing the BBC error with a 5 second delay with the same code snippet

**Comment by dbwiddis** [comment] 2018-12-07 14:41
But no error if you use a new HAL object each time?

**Comment by dbwiddis** [comment] 2018-12-07 23:17
Interestingly, I tried to replicate the error.  Without logging (the SLF4J no-op default), I think I probably had the error, as the first read of swap returned results and the rest of them gave 0.   But then when I [added logging to try to see if I could see the error messages, the problem went away](https://www.webopedia.com/TERM/H/heisenbug.html).

**Comment by spyhunter99** [comment] 2018-12-07 23:29
ha! i've used that term more than a few times. It could be classpath issue perhaps. I can work around this issue with `new SystemInfo().getHardware()` with each call. I'm using the log4j2 adapter for slf4j if that helps. Looking at the code, when `SystemInfo` is created, it creates a hardware instance and never drops it. Therefore reusing the HAL object does nothing to mitigate the issue. May i suggest adding a test scope'd dependency for something other than the no-op slf4j setup? At least that way it will be more easily detectable

**Comment by dbwiddis** [comment] 2018-12-08 02:52
The reason creating a new SystemInfo() object works is that it also recreates the objects underneath it.  this is actually useful for debugging because it suggests the problem is fixed by recreating the faulty object: in this case WindowsGlobalMemory.  So we can focus on the constructor there which generally creates new counters.

Now we need to see why it doesn't keep track of the counters if we don't re-initialize the object...

**Comment by dbwiddis** [comment] 2018-12-12 19:44
Looking at this again.  I think I know why we're seeing the symptoms we're seeing but not yet sure of the original root cause.  Outlining here what I know:

It works when you create a new instance of `WindowsGlobalMemory` (via the new SystemInfo) so we know the code in the constructor "fixes" what's broken; and that code adds the counters using `PerfDataUtil.addCounterToQuery()`.  This process adds a query for "Memory" and stores that handle in the static `queryMap`, adds the two counters to it, and stores the resulting counter handles in a static `counterMap`.

Then when you go to collect the data, you first update the query.  If successful, this method returns the timestamp, if unsuccessful, it returns zero.

- The error message `failed to update counter error code 0x800007D5` indicates this has happened.  That error code is `PDH_NO_DATA` which implies either:
  - The query does not currently contain any counters.  This is possible due to a race condition if we try to read the counter quickly after adding it.
  - The query may not contain data because the user is not running with an elevated token (see Limited User Access Support).
- So in this case we add the query (Memory) to the `disabledQueries` set.
- Problem: In WindowsGlobalMemory line 117 we do not evaluate the return value before querying the counters... we go right ahead and try to read them even if they weren't updated.

Despite the disabled queries and failed update, we query the two counter values in the next two lines (118, 119).  There is no check of the `disabledQueries` set before evaluating, so they return whatever the counter values are (without any updates).

- In the case of an invalid handle, this code removes and re-adds the counter to generate a new handle
- Problem: the query is never re-updated here.
- In future attempts to update the values, the query update is attempted but returns 0 because it's on the `disabledQueries` list, but despite the failed update, continues to attempt to read the counter (removing and adding each time).

Summary:

1. Can you humor me with one more troubleshooting step:  insert a delay between the initial creation of the WindowsGlobalMemory instance (`hal.getMemory()`) and the attempt to read the data from the created instance.  I'm guessing 1 second is more than sufficient, might only need a couple milliseconds.  This will help confirm the root cause of the problem.
2. I need to fix the code at WindowsGlobalMemory line 117 to evaluate the timestamp on failed query updates, and fallback appropriately (probably disable the counters and add the WMI backup), and definitely not read the counters.  Or if #1 proves to be a race condition, perhaps be less aggressive in "failing" a `PDH_NO_DATA` failure and give it one more shot after a delay.
3. The attempt to re-read the counter after adding it in PerfDataUtil line 128 is flawed and should be removed.

**Comment by dbwiddis** [comment] 2018-12-12 19:47
One more note... if my hunch on race condition is correct, you don't need to do the `new SystemInfo()` every time; just the first time, and after that it should work correctly.  (I still need to fix the other bugs, but knowing about the race condition will help inform a better strategy (re-try or permanently disable).)

**Comment by spyhunter99** [comment] 2018-12-12 22:11
sure thing. i'll give it a shot within the next day or so. Should i be running this test off develop or a specific release version?

**Comment by dbwiddis** [comment] 2018-12-12 22:33
Same version you've been testing on should work.  I believe the `hal.getMemory().getSwapPagesIn()` all-in-one command is too fast for the counters to be set up before queried... add in my hamhanded/buggy way of dealing with failed queries and you get the symptoms we are seeing.  I can fix my bugs but am very interested in knowing if the original issue is a race condition that we can recover from with a second query.

So just replace your previous test case
`hal.getMemory().getSwapPagesIn();`
with
```
mem = hal.getMemory();
Util.sleep(1000); // even a number as small as 0 may work!
mem.getSwapPagesIn()
```

Alternately,  try this:

```
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal= si.getHardware();
hal.getMemory(); // instantiate
while (true) {
hal.getDiskStores();
hal.getMemory().getSwapPagesIn();
}
```

**Comment by spyhunter99** [comment] 2018-12-13 03:30
Sigh. After running the same code as before, it's no longer reproducible. Not sure what's different other than a system reboot. The good news is that i found another way to reproduce....

`hal.getProcessor().isCpu64bit();`

After this call, i'll get the issues related to memory counters. If i remove this call, then it's fine.

issues with the counters occur with or without the sleep statements. This is with 3.12.0-SNAPSHOT but it's at least a few commits out of date. Here's the complete code

````
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal= si.getHardware();
hal.getProcessor().isCpu64bit();
while (true) {
hal.getDiskStores();
hal.getMemory().getSwapPagesIn();
}
````

the following also appears to fix the issue (reusing the GlobalMemory object)


````
SystemInfo si = new SystemInfo();
HardwareAbstractionLayer hal= si.getHardware();
hal.getProcessor().isCpu64bit();
GlobalMemory mem = hal.getMemory().
while (true) {
hal.getDiskStores();
mem.getSwapPagesIn();
}
````

**Comment by spyhunter99** [comment] 2018-12-13 03:33
I also managed to get the following log message, although i'm not sure if it's related to this issue or not nor am i sure how i managed to create it.

`Invalid Class Win32_PerfRawData_Counters_ThermalZoneInformation`

**Comment by dbwiddis** [comment] 2018-12-13 03:50
You may have grabbed the snapshot right before it got uploaded... I typed my comment reply while it was deploying.  As for the `isCpu64bit()` call, it has nothing to do with the "Memory" query. I'm not sure that's relevant other than possibly by tying up performance counter resources in a way that may exacerbate the race condition.

Also that WMI class I don't think is on all versions of the OS, and is unrelated to this issue.

**Comment by dbwiddis** [comment] 2018-12-13 03:53
I believe the idiom `hal.getFoo().getBar()` is problematic in multiple cases where Foo initializes the counter and Bar tries to update the counter before it's fully initialized, and I think the latest SNAPSHOT should address this problem.

**Comment by spyhunter99** [comment] 2018-12-13 15:53
just updated, there still is a sequence of events that is causing issues

**Comment by spyhunter99** [comment] 2018-12-13 15:59
i still think there is something crisscrossed between diskstore metrics and memory metrics. Could that be a possibility? If i comment out either one, the error goes away but with then both querying, the error is logged. failed to get counter 0xc0000BBC, removing and readding counter memory pages input/sec and output/sec

I also saw an issue with a different combo of code causing failed to update counter 0x800007D5, disabling future updates for memory

**Comment by dbwiddis** [comment] 2018-12-13 17:03
I would really like to see a log file with the error codes you see, alongside the various sample code you try for each one.  Unfortunately without tracing through line by line to see what messages we're getting in which order, this is difficult to debug based on the description you've provided.

I've checked the code multiple times to see if there's any overlap, and other than the very real physical correlation between swap file IO and disk IO, there's no software overlap.

**Comment by spyhunter99** [comment] 2018-12-13 18:31
Ok I'll see if I can get make a sample app to reproduce

**Comment by TChange** [comment] 2018-12-14 03:51
Hey, I got a similar Problem regarding the CPU, memory.  Here is the exception stack info.

o.util.platform.windows.PerfDataUtil - Failed to add PDH Counter: \System\Context Switches/sec, Error code: 0xC0000BB8
o.h.p.w.WindowsCentralProcessor - Unable to enumerate performance counter instances for .
java.lang.NullPointerException: null
	at oshi.util.platform.windows.PerfDataUtil.removeAllCounters(PerfDataUtil.java:227) ~[oshi-core-3.8.2.jar!/:3.8.2]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initPdhCounters(WindowsCentralProcessor.java:246) ~[oshi-core-3.8.2.jar!/:3.8.2]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:125) ~[oshi-core-3.8.2.jar!/:3.8.2]
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:64) ~[oshi-core-3.8.2.jar!/:3.8.2]

**Comment by TChange** [comment] 2018-12-16 06:32
I change the version to 3.11.0 and it works fine, thank you for your advice

**Comment by spyhunter99** [comment] 2018-12-17 15:56
https://github.com/spyhunter99/oshi-test

test project posted

**Comment by dbwiddis** [comment] 2018-12-17 16:14
Will you be posting output logs there?

**Comment by dbwiddis** [comment] 2018-12-17 21:15
File OshiDriver: 
- Fails adding the PDH counter for Memory/Swap Pages in and out 0x800007D5 (PDH_NO_DATA)
- Disables the PDH and enables WMI for this information
- The WMI appears to have trouble reading this data
  - QUESTION: Does the WMI eventually stop with the timeouts?  Sometimes the initial WMI query setup can take 20 seconds or so. 
  - Conclusion: something odd in your hardware/software setup here that I don't think OSHI can work around, as both performance counters and WMI fail to collect the data.  This may be a driver issue associated with the hard drive hosting your swap file.  (Or do you have no swap file?)

File OshiDriver1:
- Same as above but comments out a processor data fetch line
- Fails adding the counter: 0xC0000BBC (PDH_INVALID_HANDLE)
- Odd that the result is different, and this is a case that OSHI tries to recover the handle from
  - QUESTION: does the new handle also keep failing with the same error?  

File OshiDriver11:
- Looks like you reverted to the original file?
- Same error for the initial counter, but no WMI errors
  - This is common if you've already "woken up" WMI, for many queries there's an initial 20 second delay while it sets up.

Summary:
- I'm not sure where the error is in OSHI, if any. 
- Can you investigate your device driver for the drive where your swap file lives?
- Can you investigate your Performance counter setup (use perfmon.exe to try to see the same counters), also [see here](https://support.microsoft.com/en-us/help/300956/how-to-manually-rebuild-performance-counter-library-values).

**Comment by spyhunter99** [comment] 2018-12-18 00:51
i can run them both for a longer duration if you like, 5 minutes good enough? Swap file is on internal ssd, primary os partition. There's definitely a pagefile.sys file at c:\.

for perfmon, which counters am i looking for exactly?

**Comment by dbwiddis** [comment] 2018-12-18 02:20
WMI should sort itself out after approximately 20 seconds.  5 minutes may be excessive.  Perfmon counters you're looking for are `Memory\Pages Input/sec` and `Memory\Pages Output/sec`.  Also possibly `Paging File\% Usage`.  You can also try WMI on the command line:  `wmic path Win32_PerfRawData_PerfOS_Memory get PagesInputPerSec,PagesOutputPerSec` and `wmic path Win32_PerfRawData_PerfOS_PagingFile get PercentUsage`.

**Comment by dbwiddis** [comment] 2019-01-02 19:41
FYI, #729 identified a handle leak which may have caused your initial symptoms [reported here](https://github.com/oshi/oshi/issues/662#issuecomment-432125542).  This may explain why a reboot fixed a lot of the issues as well....

**Comment by spyhunter99** [comment] 2019-01-03 16:53
Great. Any idea when the next version will be cut?

**Comment by dbwiddis** [comment] 2019-01-03 17:22
3.12.1 came out on New Year's Eve and fixed that leak.

**Comment by joergkethur** [comment] 2019-04-16 16:49
hey - sorry for writin on an old ticket - but we're runnin oshi-core-3.13.0 on a hyper-v Windows Server 2016. We're calling:
`HWDiskStore[] disks = hardwareAbstractionLayer.getDiskStores();
  if (disks != null && disks.length > 0) {
	idToken += disks[0].getModel();
}`
and receiving:
`
2019-04-16 05:34:54,344 WARN  [oshi.util.platform.windows.PerfDataUtil:205] [] []  (EJB default - 3) Failed to get counter. Error code: 0xC0000BBC
2019-04-16 05:34:54,346 WARN  [xxx:341] [] []  (EJB default - 2) some error message: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
2019-04-16 05:34:54,344 WARN  [oshi.data.windows.PerfCounterQueryHandler:236] [] []  (EJB default - 3) Error querying counter \PhysicalDisk(0 C:)\Current Disk Queue Length: 0xC0000BBC`

Any Ideas what we're doing wrong?

Thx, Jörg

**Comment by dbwiddis** [comment] 2019-04-16 17:19
Without more info, not sure I can help much. Does this happen immediately or after running for a while?  Can you run Perfmon.exe and see if the named counter (\PhysicalDisk(0 C:)\Current Disk Queue Length) exists on your system and returns sane results?

**Comment by george-kay** [comment] 2019-04-17 09:56
thx for the fast reply. The issue occurs sometimes a day - not always. We check for hdd model name every 5 minutes. We checked perfmon and can see valid results - see screenshot.

![Bildschirmfoto 2019-04-17 um 11 53 36](https://user-images.githubusercontent.com/32331276/56278985-8e34c880-6107-11e9-8cf3-fc058c326bfa.png)

furthermore we got another issue - an nullpointer exception - here the detailed log:
`java.lang.NullPointerException`
	`at oshi.data.windows.PerfCounterWildcardQuery.fillCounterListMap(PerfCounterWildcardQuery.java:313)`
	`at oshi.data.windows.PerfCounterWildcardQuery.initPdhCounters(PerfCounterWildcardQuery.java:169)`
	`at oshi.data.windows.PerfCounterWildcardQuery.queryValuesWildcard(PerfCounterWildcardQuery.java:204)`
	`at oshi.hardware.platform.windows.WindowsDisks.queryReadWriteStats(WindowsDisks.java:221)`
	`at oshi.hardware.platform.windows.WindowsDisks.getDisks(WindowsDisks.java:171)`
	`at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getDiskStores(WindowsHardwareAbstractionLayer.java:88)`

**Comment by dbwiddis** [comment] 2019-04-17 22:32
Regarding #3, that could be part of the problem. Are you running a localized version of Windows?  You may need to repair your counters.

**Comment by george-kay** [comment] 2019-04-18 06:58
Thx, yes we're running the german localized Windows Server Version. You think about sth like that? https://support.microsoft.com/da-dk/help/2554336/how-to-manually-rebuild-performance-counters-for-windows-server-2008-6

**Comment by dbwiddis** [comment] 2019-04-18 18:44
Yes, that's a possibility (Still need to fix the NPE, but lack of counters at the standard 009 location may be part of the problem here).  Not sure that's the whole problem but definitely the first step in troubleshooting.  See also [here](https://github.com/oshi/oshi/issues/633#issuecomment-425179595) and [here](https://github.com/oshi/oshi/issues/762#issuecomment-453891262)

**Comment by dbwiddis** [comment] 2019-04-28 20:04
Hey @george-kay, have you had any luck with this after repairing counters?

**Comment by george-kay** [comment] 2019-06-05 11:54
hey @dbwiddis  - sorry for long delay.. but we were not successful yet. Sometime JBoss restart helps to solve the 
`[oshi.software.os.windows.WindowsOperatingSystem:162] Unable to locate English counter names in registry Perflib 009. Assuming English counters.`
issue.

So no permanent solution yet. But always only on localized Windows server versions.

**Comment by dbwiddis** [comment] 2019-08-02 22:51
Hi @george-kay. I revisted this issue today and can't find the problem.  The line number referenced for the NPE in [this comment](https://github.com/oshi/oshi/issues/662#issuecomment-484018570) does not match the current code, so you are using a version from before Jan 15 (3.12.2 or earlier).  All those classes were significantly rewritten and refactored in 3.13.0 released Jan 17 to solve multiple issues with resources, and may have already fixed the underlying cause.

Please make sure you're using the latest version of OSHI (3.13.3 as of the moment) so I can better troubleshoot.  If you do experience problems, please open a new issue with the details.

**Closed by dbwiddis** 2019-08-02 22:51 UTC
Labels: confirmed bug, i18n
