### ISSUE TITLE
M3 Macbook detection

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [oshi/oshi#2547] opened 2023-12-22 03:01 UTC
Looks like M3 Macbooks are not detected properly yet.
CPU arch detection code gets to this line and spits out a warning about the instruction being unavailable:
https://github.com/oshi/oshi/blob/35d3bd754fafdb82c72bcb0976809d8700b60aff/oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java#L111

**Comment by dbwiddis** [comment] 2023-12-22 03:42
> Looks like M3 Macbooks are not detected properly yet.

Solution: buy me an M3 Macbook and I'll fix it! ;)

Alternate solution... I'll need you to help debug.

I suspect the root cause is in this block:
https://github.com/oshi/oshi/blob/35d3bd754fafdb82c72bcb0976809d8700b60aff/oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java#L133-L144

And this bit will need a tweak:
https://github.com/oshi/oshi/blob/35d3bd754fafdb82c72bcb0976809d8700b60aff/oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java#L133-L144

**Comment by dbwiddis** [comment] 2023-12-22 05:17
A bit of digging shows the `M3_CPUFAMILY` should probably be `0x8765edea`.

The processor pair appears to be "everest" (P) and "sawtooth" (E).  

So a quick fix (until M4 comes out) would probably be to add "everest" to the line 136 comparison above and add the `M3_CPUFAMILY` value.

A better fix is noted in the comments above.

**Comment by dbwiddis** [comment] 2023-12-23 17:42
Would love for anyone with an M3 to confirm my suspicion in the above comment by either looking at their registry with IORegistryExplorer or just dumping ioreg `Ioreg -l` and finding the cpus.  Sample entry I'm looking for:
```
    | +-o cpu0@0  <class IOPlatformDevice, id 0x100000292, registered, matched, active, busy 0 (299 ms), retain 8>
    | | | {
<snip>
    | | |   "compatible" = <"apple,blizzard","ARM,v8">
<snip>
    | | | }
```
My guess is that string will say "apple,everest".

**Comment by heychazza** [comment] 2023-12-23 19:06
> Would love for anyone with an M3 to confirm my suspicion in the above comment by either looking at their registry with IORegistryExplorer or just dumping ioreg `ioreg -l` and finding the cpus. Sample entry I'm looking for:
> 
> ```
>     | +-o cpu0@0  <class IOPlatformDevice, id 0x100000292, registered, matched, active, busy 0 (299 ms), retain 8>
>     | | | {
> <snip>
>     | | |   "compatible" = <"apple,blizzard","ARM,v8">
> <snip>
>     | | | }
> ```
> 
> My guess is that string will say "apple,everest".

Hi buddy,

An M3 Max user here! I see `"compatible" = <"apple,sawtooth","ARM,v8">` - is this what you're looking for?

**Comment by dbwiddis** [comment] 2023-12-23 19:20
> An M3 Max user here! I see `"compatible" = <"apple,sawtooth","ARM,v8">` under `cpu0@0 <class IOPlatformDevice, id 0x10000029d, registered, matched,$`
> 
> and `"compatible" = <"apple,everest","ARM,v8">` under others - is this what you're looking for?

That's exactly what I needed.  Sawtooth on the e-cores, everest on the p-cores.

Thanks, I'll start working on a fix.

**Comment by heychazza** [comment] 2023-12-23 20:09
> > An M3 Max user here! I see `"compatible" = <"apple,sawtooth","ARM,v8">` under `cpu0@0 <class IOPlatformDevice, id 0x10000029d, registered, matched,$`
> > and `"compatible" = <"apple,everest","ARM,v8">` under others - is this what you're looking for?
> 
> That's exactly what I needed. Sawtooth on the e-cores, everest on the p-cores.
> 
> Thanks, I'll start working on a fix.

Awesome, glad to help — out of interest, why does Apple give these cores different names?

**Comment by dbwiddis** [comment] 2023-12-23 20:12
> out of interest, why does Apple give these cores different names?

Marketing? 😁 

There's a long tradition of naming cores by various things.  Intel is far more diverse than ARM.
https://github.com/oshi/oshi/blob/master/oshi-core/src/main/resources/oshi.architecture.properties

**Comment by dbwiddis** [comment] 2023-12-23 21:55
@heychazza If you could help just a bit more.  I've merged #2548 which I'm 99.999% sure fixes this, but before cutting a release would like a quick sanity check.

Can you fork the main branch and run the SystemInfoTest?  You should be able to copypaste this:
```bash
git clone https://github.com/oshi/oshi.git && cd oshi

./mvnw test-compile -pl oshi-core exec:java \
  -Dexec.mainClass="oshi.SystemInfoTest" \
  -Dexec.classpathScope="test"
```
The top of the output should include a section that looks like this for my M2.  Things to check:
 - The name should be Apple M3 (whatever variant of it)
 - The family should be `0x8765edea`
 - The microarchitecture should be `ARM64 SoC: Sawtooth + Everest`
 - Your P-core and E-core count and topology should be correct

```
Apple M2 Max
 1 physical CPU package(s)
 12 physical CPU core(s) (8 performance + 4 efficiency)
 12 logical CPU(s)
Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
ProcessorID: 0100000cda33d83d
Microarchitecture: ARM64 SoC: Avalanche + Blizzard
 Topology:
  LogProc  P/E Proc  Pkg NUMA PGrp
        0    E    0    0    0    0
        1    E    1    0    0    0
        2    E    2    0    0    0
        3    E    3    0    0    0
        4    P    4    0    0    0
        5    P    5    0    0    0
        6    P    6    0    0    0
        7    P    7    0    0    0
        8    P    8    0    0    0
        9    P    9    0    0    0
       10    P   10    0    0    0
       11    P   11    0    0    0
```

**Closed by dbwiddis** 2023-12-23 21:55 UTC
Labels: confirmed bug, in progress, compatibility

**Comment by heychazza** [comment] 2023-12-24 10:04
> @heychazza If you could help just a bit more. I've merged #2548 which I'm 99.999% sure fixes this, but before cutting a release would like a quick sanity check.
> 
> Can you clone the main branch and run the SystemInfoTest? You should be able to copypaste this:
> 
> ```shell
> git clone https://github.com/oshi/oshi.git && cd oshi
> 
> ./mvnw test-compile -pl oshi-core exec:java \
>   -Dexec.mainClass="oshi.SystemInfoTest" \
>   -Dexec.classpathScope="test"
> ```
> 
> The top of the output should include a section that looks like this for my M2. Things to check:
> 
> * The name should be Apple M3 (whatever variant of it)
> * The family should be `0x8765edea`
> * The microarchitecture should be `ARM64 SoC: Sawtooth + Everest` (I'll switch this to "Everest + Sawtooth" before release)
> * Your P-core and E-core count and topology should be correct
> 
> ```
> Apple M2 Max
>  1 physical CPU package(s)
>  12 physical CPU core(s) (8 performance + 4 efficiency)
>  12 logical CPU(s)
> Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
> ProcessorID: 0100000cda33d83d
> Microarchitecture: ARM64 SoC: Avalanche + Blizzard
>  Topology:
>   LogProc  P/E Proc  Pkg NUMA PGrp
>         0    E    0    0    0    0
>         1    E    1    0    0    0
>         2    E    2    0    0    0
>         3    E    3    0    0    0
>         4    P    4    0    0    0
>         5    P    5    0    0    0
>         6    P    6    0    0    0
>         7    P    7    0    0    0
>         8    P    8    0    0    0
>         9    P    9    0    0    0
>        10    P   10    0    0    0
>        11    P   11    0    0    0
> ```

Hi buddy,


```
Apple M3 Max
 1 physical CPU package(s)
 16 physical CPU core(s) (12 performance + 4 efficiency)
 16 logical CPU(s)
Identifier: Apple Inc. Family 0x8765edea Model 0 Stepping 0
ProcessorID: 0100000c8765edea
Microarchitecture: ARM64 SoC: Everest + Sawtooth
 Topology:
  LogProc  P/E Proc  Pkg NUMA PGrp
        0    E    0    0    0    0
        1    E    1    0    0    0
        2    E    2    0    0    0
        3    E    3    0    0    0
        4    P    4    0    0    0
        5    P    5    0    0    0
        6    P    6    0    0    0
        7    P    7    0    0    0
        8    P    8    0    0    0
        9    P    9    0    0    0
       10    P   10    0    0    0
       11    P   11    0    0    0
       12    P   12    0    0    0
       13    P   13    0    0    0
       14    P   14    0    0    0
       15    P   15    0    0    0
 Caches:
  ProcessorCache [L2 Unified, cacheSize=16777216, unknown associativity, lineSize=128] (per P-core)
  ProcessorCache [L2 Unified, cacheSize=4194304, unknown associativity, lineSize=128] (per E-core)
  ProcessorCache [L1 Instruction, cacheSize=131072, unknown associativity, lineSize=128] (per P-core)
  ProcessorCache [L1 Instruction, cacheSize=196608, unknown associativity, lineSize=128] (per E-core)
  ProcessorCache [L1 Data, cacheSize=131072, unknown associativity, lineSize=128] (per P-core)
  ProcessorCache [L1 Data, cacheSize=65536, unknown associativity, lineSize=128] (per E-core)
Physical Memory: 
 Available: 35.8 GiB/64 GiB
```

This looks correct to me :)

**Comment by dbwiddis** [comment] 2023-12-24 23:15
@heychazza thanks so much for your assistance here.

**Comment by hubertgrzeskowiak** [comment] 2024-01-04 04:04
@heychazza @dbwiddis Much appreciated. Thanks guys!

Sorry I wasn't able to help - I'm on M1.
